//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moduloclinicalStaff
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/", ConfigurationName="moduloclinicalStaff.ClinicalStaffService")]
    public interface ClinicalStaffService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.clinicalStaff.pe.dentalflow.com/ClinicalStaffService/getAllDentist" +
            "sBySpecialtyAndLastNameRequest", ReplyAction="http://service.clinicalStaff.pe.dentalflow.com/ClinicalStaffService/getAllDentist" +
            "sBySpecialtyAndLastNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloclinicalStaff.getAllDentistsBySpecialtyAndLastNameResponse> getAllDentistsBySpecialtyAndLastNameAsync(moduloclinicalStaff.getAllDentistsBySpecialtyAndLastNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.clinicalStaff.pe.dentalflow.com/ClinicalStaffService/updateDentist" +
            "Request", ReplyAction="http://service.clinicalStaff.pe.dentalflow.com/ClinicalStaffService/updateDentist" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloclinicalStaff.updateDentistResponse> updateDentistAsync(moduloclinicalStaff.updateDentistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.clinicalStaff.pe.dentalflow.com/ClinicalStaffService/getDentistByI" +
            "dRequest", ReplyAction="http://service.clinicalStaff.pe.dentalflow.com/ClinicalStaffService/getDentistByI" +
            "dResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloclinicalStaff.getDentistByIdResponse> getDentistByIdAsync(moduloclinicalStaff.getDentistByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.clinicalStaff.pe.dentalflow.com/ClinicalStaffService/getByIdUserRe" +
            "quest", ReplyAction="http://service.clinicalStaff.pe.dentalflow.com/ClinicalStaffService/getByIdUserRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloclinicalStaff.getByIdUserResponse> getByIdUserAsync(moduloclinicalStaff.getByIdUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.clinicalStaff.pe.dentalflow.com/ClinicalStaffService/createDentist" +
            "Request", ReplyAction="http://service.clinicalStaff.pe.dentalflow.com/ClinicalStaffService/createDentist" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloclinicalStaff.createDentistResponse> createDentistAsync(moduloclinicalStaff.createDentistRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/")]
    public partial class clinicalStaff
    {
        
        private localDateTime createdAtField;
        
        private bool disponibleField;
        
        private bool disponibleFieldSpecified;
        
        private string firstNameField;
        
        private int idField;
        
        private string lastNameField;
        
        private string licenseNumberField;
        
        private string phoneField;
        
        private specialty specialtyField;
        
        private usuario usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public localDateTime createdAt
        {
            get
            {
                return this.createdAtField;
            }
            set
            {
                this.createdAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool disponible
        {
            get
            {
                return this.disponibleField;
            }
            set
            {
                this.disponibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool disponibleSpecified
        {
            get
            {
                return this.disponibleFieldSpecified;
            }
            set
            {
                this.disponibleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string licenseNumber
        {
            get
            {
                return this.licenseNumberField;
            }
            set
            {
                this.licenseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public specialty specialty
        {
            get
            {
                return this.specialtyField;
            }
            set
            {
                this.specialtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public usuario usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/")]
    public partial class localDateTime
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/")]
    public partial class clinicalStaffResponseDto
    {
        
        private string firstNameField;
        
        private int idField;
        
        private string lastNameField;
        
        private string licenseNumberField;
        
        private string phoneField;
        
        private int specialtyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string licenseNumber
        {
            get
            {
                return this.licenseNumberField;
            }
            set
            {
                this.licenseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int specialty
        {
            get
            {
                return this.specialtyField;
            }
            set
            {
                this.specialtyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/")]
    public partial class clinicalStaffDto
    {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string licenseNumberField;
        
        private string phoneField;
        
        private int specialtyField;
        
        private int usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string licenseNumber
        {
            get
            {
                return this.licenseNumberField;
            }
            set
            {
                this.licenseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int specialty
        {
            get
            {
                return this.specialtyField;
            }
            set
            {
                this.specialtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/")]
    public partial class rol
    {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/")]
    public partial class usuario
    {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string passwordField;
        
        private rol rolField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo
        {
            get
            {
                return this.activoField;
            }
            set
            {
                this.activoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified
        {
            get
            {
                return this.activoFieldSpecified;
            }
            set
            {
                this.activoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public rol rol
        {
            get
            {
                return this.rolField;
            }
            set
            {
                this.rolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/")]
    public partial class specialty
    {
        
        private localDateTime createdAtField;
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public localDateTime createdAt
        {
            get
            {
                return this.createdAtField;
            }
            set
            {
                this.createdAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllDentistsBySpecialtyAndLastName", WrapperNamespace="http://service.clinicalStaff.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getAllDentistsBySpecialtyAndLastNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public getAllDentistsBySpecialtyAndLastNameRequest()
        {
        }
        
        public getAllDentistsBySpecialtyAndLastNameRequest(string arg0, int arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllDentistsBySpecialtyAndLastNameResponse", WrapperNamespace="http://service.clinicalStaff.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getAllDentistsBySpecialtyAndLastNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloclinicalStaff.clinicalStaff[] @return;
        
        public getAllDentistsBySpecialtyAndLastNameResponse()
        {
        }
        
        public getAllDentistsBySpecialtyAndLastNameResponse(moduloclinicalStaff.clinicalStaff[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateDentist", WrapperNamespace="http://service.clinicalStaff.pe.dentalflow.com/", IsWrapped=true)]
    public partial class updateDentistRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloclinicalStaff.clinicalStaffDto arg1;
        
        public updateDentistRequest()
        {
        }
        
        public updateDentistRequest(int arg0, moduloclinicalStaff.clinicalStaffDto arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateDentistResponse", WrapperNamespace="http://service.clinicalStaff.pe.dentalflow.com/", IsWrapped=true)]
    public partial class updateDentistResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloclinicalStaff.clinicalStaffResponseDto @return;
        
        public updateDentistResponse()
        {
        }
        
        public updateDentistResponse(moduloclinicalStaff.clinicalStaffResponseDto @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDentistById", WrapperNamespace="http://service.clinicalStaff.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getDentistByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getDentistByIdRequest()
        {
        }
        
        public getDentistByIdRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDentistByIdResponse", WrapperNamespace="http://service.clinicalStaff.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getDentistByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloclinicalStaff.clinicalStaff @return;
        
        public getDentistByIdResponse()
        {
        }
        
        public getDentistByIdResponse(moduloclinicalStaff.clinicalStaff @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByIdUser", WrapperNamespace="http://service.clinicalStaff.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getByIdUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getByIdUserRequest()
        {
        }
        
        public getByIdUserRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByIdUserResponse", WrapperNamespace="http://service.clinicalStaff.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getByIdUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloclinicalStaff.clinicalStaffResponseDto @return;
        
        public getByIdUserResponse()
        {
        }
        
        public getByIdUserResponse(moduloclinicalStaff.clinicalStaffResponseDto @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDentist", WrapperNamespace="http://service.clinicalStaff.pe.dentalflow.com/", IsWrapped=true)]
    public partial class createDentistRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg5;
        
        public createDentistRequest()
        {
        }
        
        public createDentistRequest(int arg0, int arg1, string arg2, string arg3, string arg4, string arg5)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDentistResponse", WrapperNamespace="http://service.clinicalStaff.pe.dentalflow.com/", IsWrapped=true)]
    public partial class createDentistResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.clinicalStaff.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloclinicalStaff.clinicalStaff @return;
        
        public createDentistResponse()
        {
        }
        
        public createDentistResponse(moduloclinicalStaff.clinicalStaff @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ClinicalStaffServiceChannel : moduloclinicalStaff.ClinicalStaffService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ClinicalStaffServiceClient : System.ServiceModel.ClientBase<moduloclinicalStaff.ClinicalStaffService>, moduloclinicalStaff.ClinicalStaffService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ClinicalStaffServiceClient() : 
                base(ClinicalStaffServiceClient.GetDefaultBinding(), ClinicalStaffServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ClinicalStaffServiceImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClinicalStaffServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ClinicalStaffServiceClient.GetBindingForEndpoint(endpointConfiguration), ClinicalStaffServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClinicalStaffServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ClinicalStaffServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClinicalStaffServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ClinicalStaffServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClinicalStaffServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloclinicalStaff.getAllDentistsBySpecialtyAndLastNameResponse> moduloclinicalStaff.ClinicalStaffService.getAllDentistsBySpecialtyAndLastNameAsync(moduloclinicalStaff.getAllDentistsBySpecialtyAndLastNameRequest request)
        {
            return base.Channel.getAllDentistsBySpecialtyAndLastNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloclinicalStaff.getAllDentistsBySpecialtyAndLastNameResponse> getAllDentistsBySpecialtyAndLastNameAsync(string arg0, int arg1)
        {
            moduloclinicalStaff.getAllDentistsBySpecialtyAndLastNameRequest inValue = new moduloclinicalStaff.getAllDentistsBySpecialtyAndLastNameRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((moduloclinicalStaff.ClinicalStaffService)(this)).getAllDentistsBySpecialtyAndLastNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloclinicalStaff.updateDentistResponse> moduloclinicalStaff.ClinicalStaffService.updateDentistAsync(moduloclinicalStaff.updateDentistRequest request)
        {
            return base.Channel.updateDentistAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloclinicalStaff.updateDentistResponse> updateDentistAsync(int arg0, moduloclinicalStaff.clinicalStaffDto arg1)
        {
            moduloclinicalStaff.updateDentistRequest inValue = new moduloclinicalStaff.updateDentistRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((moduloclinicalStaff.ClinicalStaffService)(this)).updateDentistAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloclinicalStaff.getDentistByIdResponse> moduloclinicalStaff.ClinicalStaffService.getDentistByIdAsync(moduloclinicalStaff.getDentistByIdRequest request)
        {
            return base.Channel.getDentistByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloclinicalStaff.getDentistByIdResponse> getDentistByIdAsync(int arg0)
        {
            moduloclinicalStaff.getDentistByIdRequest inValue = new moduloclinicalStaff.getDentistByIdRequest();
            inValue.arg0 = arg0;
            return ((moduloclinicalStaff.ClinicalStaffService)(this)).getDentistByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloclinicalStaff.getByIdUserResponse> moduloclinicalStaff.ClinicalStaffService.getByIdUserAsync(moduloclinicalStaff.getByIdUserRequest request)
        {
            return base.Channel.getByIdUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloclinicalStaff.getByIdUserResponse> getByIdUserAsync(int arg0)
        {
            moduloclinicalStaff.getByIdUserRequest inValue = new moduloclinicalStaff.getByIdUserRequest();
            inValue.arg0 = arg0;
            return ((moduloclinicalStaff.ClinicalStaffService)(this)).getByIdUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloclinicalStaff.createDentistResponse> moduloclinicalStaff.ClinicalStaffService.createDentistAsync(moduloclinicalStaff.createDentistRequest request)
        {
            return base.Channel.createDentistAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloclinicalStaff.createDentistResponse> createDentistAsync(int arg0, int arg1, string arg2, string arg3, string arg4, string arg5)
        {
            moduloclinicalStaff.createDentistRequest inValue = new moduloclinicalStaff.createDentistRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            return ((moduloclinicalStaff.ClinicalStaffService)(this)).createDentistAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ClinicalStaffServiceImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ClinicalStaffServiceImplPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:1520/ws/Dentist");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ClinicalStaffServiceClient.GetBindingForEndpoint(EndpointConfiguration.ClinicalStaffServiceImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ClinicalStaffServiceClient.GetEndpointAddress(EndpointConfiguration.ClinicalStaffServiceImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ClinicalStaffServiceImplPort,
        }
    }
}
