//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moduloClinicalStaff
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/", ConfigurationName="moduloClinicalStaff.ClinicalStaffEndpoint")]
    public interface ClinicalStaffEndpoint
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.clinicalStaff.pe.dentalflow.com/ClinicalStaffEndpoint/getDentistByIdR" +
            "equest", ReplyAction="http://soap.clinicalStaff.pe.dentalflow.com/ClinicalStaffEndpoint/getDentistByIdR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloClinicalStaff.getDentistByIdResponse> getDentistByIdAsync(moduloClinicalStaff.getDentistByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.clinicalStaff.pe.dentalflow.com/ClinicalStaffEndpoint/updateDentistRe" +
            "quest", ReplyAction="http://soap.clinicalStaff.pe.dentalflow.com/ClinicalStaffEndpoint/updateDentistRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloClinicalStaff.updateDentistResponse> updateDentistAsync(moduloClinicalStaff.updateDentistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.clinicalStaff.pe.dentalflow.com/ClinicalStaffEndpoint/createDentistRe" +
            "quest", ReplyAction="http://soap.clinicalStaff.pe.dentalflow.com/ClinicalStaffEndpoint/createDentistRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloClinicalStaff.createDentistResponse> createDentistAsync(moduloClinicalStaff.createDentistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.clinicalStaff.pe.dentalflow.com/ClinicalStaffEndpoint/getByIdUserRequ" +
            "est", ReplyAction="http://soap.clinicalStaff.pe.dentalflow.com/ClinicalStaffEndpoint/getByIdUserResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloClinicalStaff.getByIdUserResponse> getByIdUserAsync(moduloClinicalStaff.getByIdUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.clinicalStaff.pe.dentalflow.com/ClinicalStaffEndpoint/getAllDentistsB" +
            "ySpecialtyAndLastNameRequest", ReplyAction="http://soap.clinicalStaff.pe.dentalflow.com/ClinicalStaffEndpoint/getAllDentistsB" +
            "ySpecialtyAndLastNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloClinicalStaff.getAllDentistsBySpecialtyAndLastNameResponse> getAllDentistsBySpecialtyAndLastNameAsync(moduloClinicalStaff.getAllDentistsBySpecialtyAndLastNameRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/")]
    public partial class clinicalStaff
    {
        
        private localDateTime createdAtField;
        
        private bool disponibleField;
        
        private bool disponibleFieldSpecified;
        
        private string firstNameField;
        
        private int idField;
        
        private string lastNameField;
        
        private string licenseNumberField;
        
        private string phoneField;
        
        private specialty specialtyField;
        
        private usuario usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public localDateTime createdAt
        {
            get
            {
                return this.createdAtField;
            }
            set
            {
                this.createdAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool disponible
        {
            get
            {
                return this.disponibleField;
            }
            set
            {
                this.disponibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool disponibleSpecified
        {
            get
            {
                return this.disponibleFieldSpecified;
            }
            set
            {
                this.disponibleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string licenseNumber
        {
            get
            {
                return this.licenseNumberField;
            }
            set
            {
                this.licenseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public specialty specialty
        {
            get
            {
                return this.specialtyField;
            }
            set
            {
                this.specialtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public usuario usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/")]
    public partial class localDateTime
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/")]
    public partial class clinicalStaffResponseDto
    {
        
        private string firstNameField;
        
        private int idField;
        
        private string lastNameField;
        
        private string licenseNumberField;
        
        private string phoneField;
        
        private int specialtyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string licenseNumber
        {
            get
            {
                return this.licenseNumberField;
            }
            set
            {
                this.licenseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int specialty
        {
            get
            {
                return this.specialtyField;
            }
            set
            {
                this.specialtyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/")]
    public partial class clinicalStaffDto
    {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string licenseNumberField;
        
        private string phoneField;
        
        private int specialtyField;
        
        private int usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string licenseNumber
        {
            get
            {
                return this.licenseNumberField;
            }
            set
            {
                this.licenseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int specialty
        {
            get
            {
                return this.specialtyField;
            }
            set
            {
                this.specialtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/")]
    public partial class rol
    {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/")]
    public partial class usuario
    {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string passwordField;
        
        private rol rolField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo
        {
            get
            {
                return this.activoField;
            }
            set
            {
                this.activoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified
        {
            get
            {
                return this.activoFieldSpecified;
            }
            set
            {
                this.activoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public rol rol
        {
            get
            {
                return this.rolField;
            }
            set
            {
                this.rolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/")]
    public partial class specialty
    {
        
        private localDateTime createdAtField;
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public localDateTime createdAt
        {
            get
            {
                return this.createdAtField;
            }
            set
            {
                this.createdAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDentistById", WrapperNamespace="http://soap.clinicalStaff.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getDentistByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public getDentistByIdRequest()
        {
        }
        
        public getDentistByIdRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDentistByIdResponse", WrapperNamespace="http://soap.clinicalStaff.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getDentistByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloClinicalStaff.clinicalStaff @return;
        
        public getDentistByIdResponse()
        {
        }
        
        public getDentistByIdResponse(moduloClinicalStaff.clinicalStaff @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateDentist", WrapperNamespace="http://soap.clinicalStaff.pe.dentalflow.com/", IsWrapped=true)]
    public partial class updateDentistRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloClinicalStaff.clinicalStaffDto arg1;
        
        public updateDentistRequest()
        {
        }
        
        public updateDentistRequest(int arg0, moduloClinicalStaff.clinicalStaffDto arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateDentistResponse", WrapperNamespace="http://soap.clinicalStaff.pe.dentalflow.com/", IsWrapped=true)]
    public partial class updateDentistResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloClinicalStaff.clinicalStaffResponseDto @return;
        
        public updateDentistResponse()
        {
        }
        
        public updateDentistResponse(moduloClinicalStaff.clinicalStaffResponseDto @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDentist", WrapperNamespace="http://soap.clinicalStaff.pe.dentalflow.com/", IsWrapped=true)]
    public partial class createDentistRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int specialtyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string licenseNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string firstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string phone;
        
        public createDentistRequest()
        {
        }
        
        public createDentistRequest(int userId, int specialtyId, string licenseNumber, string firstName, string lastName, string phone)
        {
            this.userId = userId;
            this.specialtyId = specialtyId;
            this.licenseNumber = licenseNumber;
            this.firstName = firstName;
            this.lastName = lastName;
            this.phone = phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDentistResponse", WrapperNamespace="http://soap.clinicalStaff.pe.dentalflow.com/", IsWrapped=true)]
    public partial class createDentistResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloClinicalStaff.clinicalStaff @return;
        
        public createDentistResponse()
        {
        }
        
        public createDentistResponse(moduloClinicalStaff.clinicalStaff @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByIdUser", WrapperNamespace="http://soap.clinicalStaff.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getByIdUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getByIdUserRequest()
        {
        }
        
        public getByIdUserRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByIdUserResponse", WrapperNamespace="http://soap.clinicalStaff.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getByIdUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloClinicalStaff.clinicalStaffResponseDto @return;
        
        public getByIdUserResponse()
        {
        }
        
        public getByIdUserResponse(moduloClinicalStaff.clinicalStaffResponseDto @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllDentistsBySpecialtyAndLastName", WrapperNamespace="http://soap.clinicalStaff.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getAllDentistsBySpecialtyAndLastNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public getAllDentistsBySpecialtyAndLastNameRequest()
        {
        }
        
        public getAllDentistsBySpecialtyAndLastNameRequest(string arg0, int arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllDentistsBySpecialtyAndLastNameResponse", WrapperNamespace="http://soap.clinicalStaff.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getAllDentistsBySpecialtyAndLastNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.clinicalStaff.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloClinicalStaff.clinicalStaff[] @return;
        
        public getAllDentistsBySpecialtyAndLastNameResponse()
        {
        }
        
        public getAllDentistsBySpecialtyAndLastNameResponse(moduloClinicalStaff.clinicalStaff[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ClinicalStaffEndpointChannel : moduloClinicalStaff.ClinicalStaffEndpoint, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ClinicalStaffEndpointClient : System.ServiceModel.ClientBase<moduloClinicalStaff.ClinicalStaffEndpoint>, moduloClinicalStaff.ClinicalStaffEndpoint
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ClinicalStaffEndpointClient() : 
                base(ClinicalStaffEndpointClient.GetDefaultBinding(), ClinicalStaffEndpointClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ClinicalStaffEndpointPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClinicalStaffEndpointClient(EndpointConfiguration endpointConfiguration) : 
                base(ClinicalStaffEndpointClient.GetBindingForEndpoint(endpointConfiguration), ClinicalStaffEndpointClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClinicalStaffEndpointClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ClinicalStaffEndpointClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClinicalStaffEndpointClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ClinicalStaffEndpointClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClinicalStaffEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloClinicalStaff.getDentistByIdResponse> moduloClinicalStaff.ClinicalStaffEndpoint.getDentistByIdAsync(moduloClinicalStaff.getDentistByIdRequest request)
        {
            return base.Channel.getDentistByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloClinicalStaff.getDentistByIdResponse> getDentistByIdAsync(int id)
        {
            moduloClinicalStaff.getDentistByIdRequest inValue = new moduloClinicalStaff.getDentistByIdRequest();
            inValue.id = id;
            return ((moduloClinicalStaff.ClinicalStaffEndpoint)(this)).getDentistByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloClinicalStaff.updateDentistResponse> moduloClinicalStaff.ClinicalStaffEndpoint.updateDentistAsync(moduloClinicalStaff.updateDentistRequest request)
        {
            return base.Channel.updateDentistAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloClinicalStaff.updateDentistResponse> updateDentistAsync(int arg0, moduloClinicalStaff.clinicalStaffDto arg1)
        {
            moduloClinicalStaff.updateDentistRequest inValue = new moduloClinicalStaff.updateDentistRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((moduloClinicalStaff.ClinicalStaffEndpoint)(this)).updateDentistAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloClinicalStaff.createDentistResponse> moduloClinicalStaff.ClinicalStaffEndpoint.createDentistAsync(moduloClinicalStaff.createDentistRequest request)
        {
            return base.Channel.createDentistAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloClinicalStaff.createDentistResponse> createDentistAsync(int userId, int specialtyId, string licenseNumber, string firstName, string lastName, string phone)
        {
            moduloClinicalStaff.createDentistRequest inValue = new moduloClinicalStaff.createDentistRequest();
            inValue.userId = userId;
            inValue.specialtyId = specialtyId;
            inValue.licenseNumber = licenseNumber;
            inValue.firstName = firstName;
            inValue.lastName = lastName;
            inValue.phone = phone;
            return ((moduloClinicalStaff.ClinicalStaffEndpoint)(this)).createDentistAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloClinicalStaff.getByIdUserResponse> moduloClinicalStaff.ClinicalStaffEndpoint.getByIdUserAsync(moduloClinicalStaff.getByIdUserRequest request)
        {
            return base.Channel.getByIdUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloClinicalStaff.getByIdUserResponse> getByIdUserAsync(int arg0)
        {
            moduloClinicalStaff.getByIdUserRequest inValue = new moduloClinicalStaff.getByIdUserRequest();
            inValue.arg0 = arg0;
            return ((moduloClinicalStaff.ClinicalStaffEndpoint)(this)).getByIdUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloClinicalStaff.getAllDentistsBySpecialtyAndLastNameResponse> moduloClinicalStaff.ClinicalStaffEndpoint.getAllDentistsBySpecialtyAndLastNameAsync(moduloClinicalStaff.getAllDentistsBySpecialtyAndLastNameRequest request)
        {
            return base.Channel.getAllDentistsBySpecialtyAndLastNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloClinicalStaff.getAllDentistsBySpecialtyAndLastNameResponse> getAllDentistsBySpecialtyAndLastNameAsync(string arg0, int arg1)
        {
            moduloClinicalStaff.getAllDentistsBySpecialtyAndLastNameRequest inValue = new moduloClinicalStaff.getAllDentistsBySpecialtyAndLastNameRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((moduloClinicalStaff.ClinicalStaffEndpoint)(this)).getAllDentistsBySpecialtyAndLastNameAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ClinicalStaffEndpointPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ClinicalStaffEndpointPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:1520/ws/clinicalStaff");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ClinicalStaffEndpointClient.GetBindingForEndpoint(EndpointConfiguration.ClinicalStaffEndpointPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ClinicalStaffEndpointClient.GetEndpointAddress(EndpointConfiguration.ClinicalStaffEndpointPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ClinicalStaffEndpointPort,
        }
    }
}
