//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moduloEspecialidades
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.specialty.pe.dentalflow.com/", ConfigurationName="moduloEspecialidades.SpecialtyService")]
    public interface SpecialtyService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.specialty.pe.dentalflow.com/SpecialtyService/createSpecialtyReques" +
            "t", ReplyAction="http://service.specialty.pe.dentalflow.com/SpecialtyService/createSpecialtyRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloEspecialidades.createSpecialtyResponse> createSpecialtyAsync(moduloEspecialidades.createSpecialtyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.specialty.pe.dentalflow.com/SpecialtyService/updateSpecialtyReques" +
            "t", ReplyAction="http://service.specialty.pe.dentalflow.com/SpecialtyService/updateSpecialtyRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloEspecialidades.updateSpecialtyResponse> updateSpecialtyAsync(moduloEspecialidades.updateSpecialtyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.specialty.pe.dentalflow.com/SpecialtyService/getAllSpecialtiesRequ" +
            "est", ReplyAction="http://service.specialty.pe.dentalflow.com/SpecialtyService/getAllSpecialtiesResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloEspecialidades.getAllSpecialtiesResponse> getAllSpecialtiesAsync(moduloEspecialidades.getAllSpecialtiesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.specialty.pe.dentalflow.com/")]
    public partial class specialty
    {
        
        private localDateTime createdAtField;
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public localDateTime createdAt
        {
            get
            {
                return this.createdAtField;
            }
            set
            {
                this.createdAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.specialty.pe.dentalflow.com/")]
    public partial class localDateTime
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createSpecialty", WrapperNamespace="http://service.specialty.pe.dentalflow.com/", IsWrapped=true)]
    public partial class createSpecialtyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.specialty.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public createSpecialtyRequest()
        {
        }
        
        public createSpecialtyRequest(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createSpecialtyResponse", WrapperNamespace="http://service.specialty.pe.dentalflow.com/", IsWrapped=true)]
    public partial class createSpecialtyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.specialty.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloEspecialidades.specialty @return;
        
        public createSpecialtyResponse()
        {
        }
        
        public createSpecialtyResponse(moduloEspecialidades.specialty @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateSpecialty", WrapperNamespace="http://service.specialty.pe.dentalflow.com/", IsWrapped=true)]
    public partial class updateSpecialtyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.specialty.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.specialty.pe.dentalflow.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public updateSpecialtyRequest()
        {
        }
        
        public updateSpecialtyRequest(int arg0, string arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateSpecialtyResponse", WrapperNamespace="http://service.specialty.pe.dentalflow.com/", IsWrapped=true)]
    public partial class updateSpecialtyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.specialty.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloEspecialidades.specialty @return;
        
        public updateSpecialtyResponse()
        {
        }
        
        public updateSpecialtyResponse(moduloEspecialidades.specialty @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllSpecialties", WrapperNamespace="http://service.specialty.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getAllSpecialtiesRequest
    {
        
        public getAllSpecialtiesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllSpecialtiesResponse", WrapperNamespace="http://service.specialty.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getAllSpecialtiesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.specialty.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloEspecialidades.specialty[] @return;
        
        public getAllSpecialtiesResponse()
        {
        }
        
        public getAllSpecialtiesResponse(moduloEspecialidades.specialty[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface SpecialtyServiceChannel : moduloEspecialidades.SpecialtyService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class SpecialtyServiceClient : System.ServiceModel.ClientBase<moduloEspecialidades.SpecialtyService>, moduloEspecialidades.SpecialtyService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SpecialtyServiceClient() : 
                base(SpecialtyServiceClient.GetDefaultBinding(), SpecialtyServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SpecialtyServiceImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SpecialtyServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SpecialtyServiceClient.GetBindingForEndpoint(endpointConfiguration), SpecialtyServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SpecialtyServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SpecialtyServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SpecialtyServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SpecialtyServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SpecialtyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloEspecialidades.createSpecialtyResponse> moduloEspecialidades.SpecialtyService.createSpecialtyAsync(moduloEspecialidades.createSpecialtyRequest request)
        {
            return base.Channel.createSpecialtyAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloEspecialidades.createSpecialtyResponse> createSpecialtyAsync(string arg0)
        {
            moduloEspecialidades.createSpecialtyRequest inValue = new moduloEspecialidades.createSpecialtyRequest();
            inValue.arg0 = arg0;
            return ((moduloEspecialidades.SpecialtyService)(this)).createSpecialtyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloEspecialidades.updateSpecialtyResponse> moduloEspecialidades.SpecialtyService.updateSpecialtyAsync(moduloEspecialidades.updateSpecialtyRequest request)
        {
            return base.Channel.updateSpecialtyAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloEspecialidades.updateSpecialtyResponse> updateSpecialtyAsync(int arg0, string arg1)
        {
            moduloEspecialidades.updateSpecialtyRequest inValue = new moduloEspecialidades.updateSpecialtyRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((moduloEspecialidades.SpecialtyService)(this)).updateSpecialtyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloEspecialidades.getAllSpecialtiesResponse> moduloEspecialidades.SpecialtyService.getAllSpecialtiesAsync(moduloEspecialidades.getAllSpecialtiesRequest request)
        {
            return base.Channel.getAllSpecialtiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloEspecialidades.getAllSpecialtiesResponse> getAllSpecialtiesAsync()
        {
            moduloEspecialidades.getAllSpecialtiesRequest inValue = new moduloEspecialidades.getAllSpecialtiesRequest();
            return ((moduloEspecialidades.SpecialtyService)(this)).getAllSpecialtiesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SpecialtyServiceImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SpecialtyServiceImplPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:1520/ws/Specialty");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SpecialtyServiceClient.GetBindingForEndpoint(EndpointConfiguration.SpecialtyServiceImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SpecialtyServiceClient.GetEndpointAddress(EndpointConfiguration.SpecialtyServiceImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            SpecialtyServiceImplPort,
        }
    }
}
