//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moduloTipoCita
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap.appointment.pe.dentalflow.com/", ConfigurationName="moduloTipoCita.AppointmentTypeEndpoint")]
    public interface AppointmentTypeEndpoint
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.appointment.pe.dentalflow.com/AppointmentTypeEndpoint/updateTypeReque" +
            "st", ReplyAction="http://soap.appointment.pe.dentalflow.com/AppointmentTypeEndpoint/updateTypeRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloTipoCita.updateTypeResponse> updateTypeAsync(moduloTipoCita.updateTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.appointment.pe.dentalflow.com/AppointmentTypeEndpoint/findTypeRequest" +
            "", ReplyAction="http://soap.appointment.pe.dentalflow.com/AppointmentTypeEndpoint/findTypeRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloTipoCita.findTypeResponse> findTypeAsync(moduloTipoCita.findTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.appointment.pe.dentalflow.com/AppointmentTypeEndpoint/createAppointme" +
            "ntTypeRequest", ReplyAction="http://soap.appointment.pe.dentalflow.com/AppointmentTypeEndpoint/createAppointme" +
            "ntTypeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloTipoCita.createAppointmentTypeResponse> createAppointmentTypeAsync(moduloTipoCita.createAppointmentTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.appointment.pe.dentalflow.com/AppointmentTypeEndpoint/getAllAppointme" +
            "ntTypesRequest", ReplyAction="http://soap.appointment.pe.dentalflow.com/AppointmentTypeEndpoint/getAllAppointme" +
            "ntTypesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloTipoCita.getAllAppointmentTypesResponse> getAllAppointmentTypesAsync(moduloTipoCita.getAllAppointmentTypesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.appointment.pe.dentalflow.com/")]
    public partial class appointmentType
    {
        
        private localDateTime createdAtField;
        
        private int durationMinutesField;
        
        private bool durationMinutesFieldSpecified;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        private decimal priceField;
        
        private bool priceFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public localDateTime createdAt
        {
            get
            {
                return this.createdAtField;
            }
            set
            {
                this.createdAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int durationMinutes
        {
            get
            {
                return this.durationMinutesField;
            }
            set
            {
                this.durationMinutesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool durationMinutesSpecified
        {
            get
            {
                return this.durationMinutesFieldSpecified;
            }
            set
            {
                this.durationMinutesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified
        {
            get
            {
                return this.priceFieldSpecified;
            }
            set
            {
                this.priceFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.appointment.pe.dentalflow.com/")]
    public partial class localDateTime
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateType", WrapperNamespace="http://soap.appointment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class updateTypeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.appointment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.appointment.pe.dentalflow.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloTipoCita.appointmentType arg1;
        
        public updateTypeRequest()
        {
        }
        
        public updateTypeRequest(long arg0, moduloTipoCita.appointmentType arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateTypeResponse", WrapperNamespace="http://soap.appointment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class updateTypeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.appointment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public updateTypeResponse()
        {
        }
        
        public updateTypeResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findType", WrapperNamespace="http://soap.appointment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class findTypeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.appointment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public findTypeRequest()
        {
        }
        
        public findTypeRequest(long arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findTypeResponse", WrapperNamespace="http://soap.appointment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class findTypeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.appointment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloTipoCita.appointmentType @return;
        
        public findTypeResponse()
        {
        }
        
        public findTypeResponse(moduloTipoCita.appointmentType @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createAppointmentType", WrapperNamespace="http://soap.appointment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class createAppointmentTypeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.appointment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.appointment.pe.dentalflow.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int durationMinutes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.appointment.pe.dentalflow.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal price;
        
        public createAppointmentTypeRequest()
        {
        }
        
        public createAppointmentTypeRequest(string name, int durationMinutes, decimal price)
        {
            this.name = name;
            this.durationMinutes = durationMinutes;
            this.price = price;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createAppointmentTypeResponse", WrapperNamespace="http://soap.appointment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class createAppointmentTypeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.appointment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloTipoCita.appointmentType @return;
        
        public createAppointmentTypeResponse()
        {
        }
        
        public createAppointmentTypeResponse(moduloTipoCita.appointmentType @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllAppointmentTypes", WrapperNamespace="http://soap.appointment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getAllAppointmentTypesRequest
    {
        
        public getAllAppointmentTypesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllAppointmentTypesResponse", WrapperNamespace="http://soap.appointment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getAllAppointmentTypesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.appointment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloTipoCita.appointmentType[] @return;
        
        public getAllAppointmentTypesResponse()
        {
        }
        
        public getAllAppointmentTypesResponse(moduloTipoCita.appointmentType[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface AppointmentTypeEndpointChannel : moduloTipoCita.AppointmentTypeEndpoint, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class AppointmentTypeEndpointClient : System.ServiceModel.ClientBase<moduloTipoCita.AppointmentTypeEndpoint>, moduloTipoCita.AppointmentTypeEndpoint
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AppointmentTypeEndpointClient() : 
                base(AppointmentTypeEndpointClient.GetDefaultBinding(), AppointmentTypeEndpointClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AppointmentTypeEndpointPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppointmentTypeEndpointClient(EndpointConfiguration endpointConfiguration) : 
                base(AppointmentTypeEndpointClient.GetBindingForEndpoint(endpointConfiguration), AppointmentTypeEndpointClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppointmentTypeEndpointClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AppointmentTypeEndpointClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppointmentTypeEndpointClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AppointmentTypeEndpointClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppointmentTypeEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloTipoCita.updateTypeResponse> moduloTipoCita.AppointmentTypeEndpoint.updateTypeAsync(moduloTipoCita.updateTypeRequest request)
        {
            return base.Channel.updateTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloTipoCita.updateTypeResponse> updateTypeAsync(long arg0, moduloTipoCita.appointmentType arg1)
        {
            moduloTipoCita.updateTypeRequest inValue = new moduloTipoCita.updateTypeRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((moduloTipoCita.AppointmentTypeEndpoint)(this)).updateTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloTipoCita.findTypeResponse> moduloTipoCita.AppointmentTypeEndpoint.findTypeAsync(moduloTipoCita.findTypeRequest request)
        {
            return base.Channel.findTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloTipoCita.findTypeResponse> findTypeAsync(long arg0)
        {
            moduloTipoCita.findTypeRequest inValue = new moduloTipoCita.findTypeRequest();
            inValue.arg0 = arg0;
            return ((moduloTipoCita.AppointmentTypeEndpoint)(this)).findTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloTipoCita.createAppointmentTypeResponse> moduloTipoCita.AppointmentTypeEndpoint.createAppointmentTypeAsync(moduloTipoCita.createAppointmentTypeRequest request)
        {
            return base.Channel.createAppointmentTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloTipoCita.createAppointmentTypeResponse> createAppointmentTypeAsync(string name, int durationMinutes, decimal price)
        {
            moduloTipoCita.createAppointmentTypeRequest inValue = new moduloTipoCita.createAppointmentTypeRequest();
            inValue.name = name;
            inValue.durationMinutes = durationMinutes;
            inValue.price = price;
            return ((moduloTipoCita.AppointmentTypeEndpoint)(this)).createAppointmentTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloTipoCita.getAllAppointmentTypesResponse> moduloTipoCita.AppointmentTypeEndpoint.getAllAppointmentTypesAsync(moduloTipoCita.getAllAppointmentTypesRequest request)
        {
            return base.Channel.getAllAppointmentTypesAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloTipoCita.getAllAppointmentTypesResponse> getAllAppointmentTypesAsync()
        {
            moduloTipoCita.getAllAppointmentTypesRequest inValue = new moduloTipoCita.getAllAppointmentTypesRequest();
            return ((moduloTipoCita.AppointmentTypeEndpoint)(this)).getAllAppointmentTypesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AppointmentTypeEndpointPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AppointmentTypeEndpointPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:1520/ws/appointmentType");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AppointmentTypeEndpointClient.GetBindingForEndpoint(EndpointConfiguration.AppointmentTypeEndpointPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AppointmentTypeEndpointClient.GetEndpointAddress(EndpointConfiguration.AppointmentTypeEndpointPort);
        }
        
        public enum EndpointConfiguration
        {
            
            AppointmentTypeEndpointPort,
        }
    }
}
