//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicioSesionTratamiento
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://impl.service.treatment.pe.dentalflow.com/", ConfigurationName="servicioSesionTratamiento.SesionTratamientoServiceImpl")]
    public interface SesionTratamientoServiceImpl
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://impl.service.treatment.pe.dentalflow.com/SesionTratamientoServiceImpl/getA" +
            "llSesionesByIdTratamientoRequest", ReplyAction="http://impl.service.treatment.pe.dentalflow.com/SesionTratamientoServiceImpl/getA" +
            "llSesionesByIdTratamientoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<servicioSesionTratamiento.getAllSesionesByIdTratamientoResponse> getAllSesionesByIdTratamientoAsync(servicioSesionTratamiento.getAllSesionesByIdTratamientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://impl.service.treatment.pe.dentalflow.com/SesionTratamientoServiceImpl/actu" +
            "alizarSesionRequest", ReplyAction="http://impl.service.treatment.pe.dentalflow.com/SesionTratamientoServiceImpl/actu" +
            "alizarSesionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<servicioSesionTratamiento.actualizarSesionResponse> actualizarSesionAsync(servicioSesionTratamiento.actualizarSesionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://impl.service.treatment.pe.dentalflow.com/SesionTratamientoServiceImpl/canc" +
            "elarSesionRequest", ReplyAction="http://impl.service.treatment.pe.dentalflow.com/SesionTratamientoServiceImpl/canc" +
            "elarSesionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<servicioSesionTratamiento.cancelarSesionResponse> cancelarSesionAsync(servicioSesionTratamiento.cancelarSesionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://impl.service.treatment.pe.dentalflow.com/SesionTratamientoServiceImpl/sesi" +
            "onesParahoyRequest", ReplyAction="http://impl.service.treatment.pe.dentalflow.com/SesionTratamientoServiceImpl/sesi" +
            "onesParahoyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<servicioSesionTratamiento.sesionesParahoyResponse> sesionesParahoyAsync(servicioSesionTratamiento.sesionesParahoyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://impl.service.treatment.pe.dentalflow.com/SesionTratamientoServiceImpl/regi" +
            "strarSesionRequest", ReplyAction="http://impl.service.treatment.pe.dentalflow.com/SesionTratamientoServiceImpl/regi" +
            "strarSesionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<servicioSesionTratamiento.registrarSesionResponse> registrarSesionAsync(servicioSesionTratamiento.registrarSesionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://impl.service.treatment.pe.dentalflow.com/SesionTratamientoServiceImpl/getS" +
            "esionRequest", ReplyAction="http://impl.service.treatment.pe.dentalflow.com/SesionTratamientoServiceImpl/getS" +
            "esionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<servicioSesionTratamiento.getSesionResponse> getSesionAsync(servicioSesionTratamiento.getSesionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.service.treatment.pe.dentalflow.com/")]
    public partial class sesionTratamientoResponseDto
    {
        
        private int idSesionField;
        
        private string nombrePacienteField;
        
        private string apellidoPacienteField;
        
        private string dniField;
        
        private string fechaProgramadaField;
        
        private string fechaRealizadaField;
        
        private decimal costoParcialField;
        
        private bool costoParcialFieldSpecified;
        
        private string observacionesField;
        
        private string estadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idSesion
        {
            get
            {
                return this.idSesionField;
            }
            set
            {
                this.idSesionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombrePaciente
        {
            get
            {
                return this.nombrePacienteField;
            }
            set
            {
                this.nombrePacienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string apellidoPaciente
        {
            get
            {
                return this.apellidoPacienteField;
            }
            set
            {
                this.apellidoPacienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string dni
        {
            get
            {
                return this.dniField;
            }
            set
            {
                this.dniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fechaProgramada
        {
            get
            {
                return this.fechaProgramadaField;
            }
            set
            {
                this.fechaProgramadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string fechaRealizada
        {
            get
            {
                return this.fechaRealizadaField;
            }
            set
            {
                this.fechaRealizadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal costoParcial
        {
            get
            {
                return this.costoParcialField;
            }
            set
            {
                this.costoParcialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool costoParcialSpecified
        {
            get
            {
                return this.costoParcialFieldSpecified;
            }
            set
            {
                this.costoParcialFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string observaciones
        {
            get
            {
                return this.observacionesField;
            }
            set
            {
                this.observacionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.service.treatment.pe.dentalflow.com/")]
    public partial class sesionTratamientoRegisterRequestDto
    {
        
        private int idTratamientoField;
        
        private string fechaProgramadaField;
        
        private decimal costoParcialField;
        
        private bool costoParcialFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idTratamiento
        {
            get
            {
                return this.idTratamientoField;
            }
            set
            {
                this.idTratamientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fechaProgramada
        {
            get
            {
                return this.fechaProgramadaField;
            }
            set
            {
                this.fechaProgramadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal costoParcial
        {
            get
            {
                return this.costoParcialField;
            }
            set
            {
                this.costoParcialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool costoParcialSpecified
        {
            get
            {
                return this.costoParcialFieldSpecified;
            }
            set
            {
                this.costoParcialFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.service.treatment.pe.dentalflow.com/")]
    public partial class sesionTratamientoUpdateRequestDto
    {
        
        private string fechaRealizadaField;
        
        private string observacionesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fechaRealizada
        {
            get
            {
                return this.fechaRealizadaField;
            }
            set
            {
                this.fechaRealizadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string observaciones
        {
            get
            {
                return this.observacionesField;
            }
            set
            {
                this.observacionesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllSesionesByIdTratamiento", WrapperNamespace="http://impl.service.treatment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getAllSesionesByIdTratamientoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.treatment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getAllSesionesByIdTratamientoRequest()
        {
        }
        
        public getAllSesionesByIdTratamientoRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllSesionesByIdTratamientoResponse", WrapperNamespace="http://impl.service.treatment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getAllSesionesByIdTratamientoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.treatment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public servicioSesionTratamiento.sesionTratamientoResponseDto[] @return;
        
        public getAllSesionesByIdTratamientoResponse()
        {
        }
        
        public getAllSesionesByIdTratamientoResponse(servicioSesionTratamiento.sesionTratamientoResponseDto[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarSesion", WrapperNamespace="http://impl.service.treatment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class actualizarSesionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.treatment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public servicioSesionTratamiento.sesionTratamientoUpdateRequestDto arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.treatment.pe.dentalflow.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public actualizarSesionRequest()
        {
        }
        
        public actualizarSesionRequest(servicioSesionTratamiento.sesionTratamientoUpdateRequestDto arg0, int arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarSesionResponse", WrapperNamespace="http://impl.service.treatment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class actualizarSesionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.treatment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public actualizarSesionResponse()
        {
        }
        
        public actualizarSesionResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelarSesion", WrapperNamespace="http://impl.service.treatment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class cancelarSesionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.treatment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public cancelarSesionRequest()
        {
        }
        
        public cancelarSesionRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelarSesionResponse", WrapperNamespace="http://impl.service.treatment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class cancelarSesionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.treatment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public cancelarSesionResponse()
        {
        }
        
        public cancelarSesionResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sesionesParahoy", WrapperNamespace="http://impl.service.treatment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class sesionesParahoyRequest
    {
        
        public sesionesParahoyRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sesionesParahoyResponse", WrapperNamespace="http://impl.service.treatment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class sesionesParahoyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.treatment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public servicioSesionTratamiento.sesionTratamientoResponseDto[] @return;
        
        public sesionesParahoyResponse()
        {
        }
        
        public sesionesParahoyResponse(servicioSesionTratamiento.sesionTratamientoResponseDto[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarSesion", WrapperNamespace="http://impl.service.treatment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class registrarSesionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.treatment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public servicioSesionTratamiento.sesionTratamientoRegisterRequestDto arg0;
        
        public registrarSesionRequest()
        {
        }
        
        public registrarSesionRequest(servicioSesionTratamiento.sesionTratamientoRegisterRequestDto arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarSesionResponse", WrapperNamespace="http://impl.service.treatment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class registrarSesionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.treatment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public registrarSesionResponse()
        {
        }
        
        public registrarSesionResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSesion", WrapperNamespace="http://impl.service.treatment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getSesionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.treatment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getSesionRequest()
        {
        }
        
        public getSesionRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSesionResponse", WrapperNamespace="http://impl.service.treatment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getSesionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.treatment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public servicioSesionTratamiento.sesionTratamientoResponseDto @return;
        
        public getSesionResponse()
        {
        }
        
        public getSesionResponse(servicioSesionTratamiento.sesionTratamientoResponseDto @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface SesionTratamientoServiceImplChannel : servicioSesionTratamiento.SesionTratamientoServiceImpl, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class SesionTratamientoServiceImplClient : System.ServiceModel.ClientBase<servicioSesionTratamiento.SesionTratamientoServiceImpl>, servicioSesionTratamiento.SesionTratamientoServiceImpl
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SesionTratamientoServiceImplClient() : 
                base(SesionTratamientoServiceImplClient.GetDefaultBinding(), SesionTratamientoServiceImplClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SesionTratamientoServiceImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SesionTratamientoServiceImplClient(EndpointConfiguration endpointConfiguration) : 
                base(SesionTratamientoServiceImplClient.GetBindingForEndpoint(endpointConfiguration), SesionTratamientoServiceImplClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SesionTratamientoServiceImplClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SesionTratamientoServiceImplClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SesionTratamientoServiceImplClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SesionTratamientoServiceImplClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SesionTratamientoServiceImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<servicioSesionTratamiento.getAllSesionesByIdTratamientoResponse> servicioSesionTratamiento.SesionTratamientoServiceImpl.getAllSesionesByIdTratamientoAsync(servicioSesionTratamiento.getAllSesionesByIdTratamientoRequest request)
        {
            return base.Channel.getAllSesionesByIdTratamientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<servicioSesionTratamiento.getAllSesionesByIdTratamientoResponse> getAllSesionesByIdTratamientoAsync(int arg0)
        {
            servicioSesionTratamiento.getAllSesionesByIdTratamientoRequest inValue = new servicioSesionTratamiento.getAllSesionesByIdTratamientoRequest();
            inValue.arg0 = arg0;
            return ((servicioSesionTratamiento.SesionTratamientoServiceImpl)(this)).getAllSesionesByIdTratamientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<servicioSesionTratamiento.actualizarSesionResponse> servicioSesionTratamiento.SesionTratamientoServiceImpl.actualizarSesionAsync(servicioSesionTratamiento.actualizarSesionRequest request)
        {
            return base.Channel.actualizarSesionAsync(request);
        }
        
        public System.Threading.Tasks.Task<servicioSesionTratamiento.actualizarSesionResponse> actualizarSesionAsync(servicioSesionTratamiento.sesionTratamientoUpdateRequestDto arg0, int arg1)
        {
            servicioSesionTratamiento.actualizarSesionRequest inValue = new servicioSesionTratamiento.actualizarSesionRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((servicioSesionTratamiento.SesionTratamientoServiceImpl)(this)).actualizarSesionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<servicioSesionTratamiento.cancelarSesionResponse> servicioSesionTratamiento.SesionTratamientoServiceImpl.cancelarSesionAsync(servicioSesionTratamiento.cancelarSesionRequest request)
        {
            return base.Channel.cancelarSesionAsync(request);
        }
        
        public System.Threading.Tasks.Task<servicioSesionTratamiento.cancelarSesionResponse> cancelarSesionAsync(int arg0)
        {
            servicioSesionTratamiento.cancelarSesionRequest inValue = new servicioSesionTratamiento.cancelarSesionRequest();
            inValue.arg0 = arg0;
            return ((servicioSesionTratamiento.SesionTratamientoServiceImpl)(this)).cancelarSesionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<servicioSesionTratamiento.sesionesParahoyResponse> servicioSesionTratamiento.SesionTratamientoServiceImpl.sesionesParahoyAsync(servicioSesionTratamiento.sesionesParahoyRequest request)
        {
            return base.Channel.sesionesParahoyAsync(request);
        }
        
        public System.Threading.Tasks.Task<servicioSesionTratamiento.sesionesParahoyResponse> sesionesParahoyAsync()
        {
            servicioSesionTratamiento.sesionesParahoyRequest inValue = new servicioSesionTratamiento.sesionesParahoyRequest();
            return ((servicioSesionTratamiento.SesionTratamientoServiceImpl)(this)).sesionesParahoyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<servicioSesionTratamiento.registrarSesionResponse> servicioSesionTratamiento.SesionTratamientoServiceImpl.registrarSesionAsync(servicioSesionTratamiento.registrarSesionRequest request)
        {
            return base.Channel.registrarSesionAsync(request);
        }
        
        public System.Threading.Tasks.Task<servicioSesionTratamiento.registrarSesionResponse> registrarSesionAsync(servicioSesionTratamiento.sesionTratamientoRegisterRequestDto arg0)
        {
            servicioSesionTratamiento.registrarSesionRequest inValue = new servicioSesionTratamiento.registrarSesionRequest();
            inValue.arg0 = arg0;
            return ((servicioSesionTratamiento.SesionTratamientoServiceImpl)(this)).registrarSesionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<servicioSesionTratamiento.getSesionResponse> servicioSesionTratamiento.SesionTratamientoServiceImpl.getSesionAsync(servicioSesionTratamiento.getSesionRequest request)
        {
            return base.Channel.getSesionAsync(request);
        }
        
        public System.Threading.Tasks.Task<servicioSesionTratamiento.getSesionResponse> getSesionAsync(int arg0)
        {
            servicioSesionTratamiento.getSesionRequest inValue = new servicioSesionTratamiento.getSesionRequest();
            inValue.arg0 = arg0;
            return ((servicioSesionTratamiento.SesionTratamientoServiceImpl)(this)).getSesionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SesionTratamientoServiceImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SesionTratamientoServiceImplPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:1520/ws/sesionTratamiento");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SesionTratamientoServiceImplClient.GetBindingForEndpoint(EndpointConfiguration.SesionTratamientoServiceImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SesionTratamientoServiceImplClient.GetEndpointAddress(EndpointConfiguration.SesionTratamientoServiceImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            SesionTratamientoServiceImplPort,
        }
    }
}
