//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moduloMaterial
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap.material.pe.dentalflow.com/", ConfigurationName="moduloMaterial.MaterialEndpoint")]
    public interface MaterialEndpoint
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.material.pe.dentalflow.com/MaterialEndpoint/materialGetAllRequest", ReplyAction="http://soap.material.pe.dentalflow.com/MaterialEndpoint/materialGetAllResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloMaterial.materialGetAllResponse> materialGetAllAsync(moduloMaterial.materialGetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.material.pe.dentalflow.com/MaterialEndpoint/materialUpdateRequest", ReplyAction="http://soap.material.pe.dentalflow.com/MaterialEndpoint/materialUpdateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloMaterial.materialUpdateResponse> materialUpdateAsync(moduloMaterial.materialUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.material.pe.dentalflow.com/MaterialEndpoint/materialDeleteRequest", ReplyAction="http://soap.material.pe.dentalflow.com/MaterialEndpoint/materialDeleteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloMaterial.materialDeleteResponse> materialDeleteAsync(moduloMaterial.materialDeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.material.pe.dentalflow.com/MaterialEndpoint/stockCriticoRequest", ReplyAction="http://soap.material.pe.dentalflow.com/MaterialEndpoint/stockCriticoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloMaterial.stockCriticoResponse> stockCriticoAsync(moduloMaterial.stockCriticoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.material.pe.dentalflow.com/MaterialEndpoint/materialCreateRequest", ReplyAction="http://soap.material.pe.dentalflow.com/MaterialEndpoint/materialCreateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloMaterial.materialCreateResponse> materialCreateAsync(moduloMaterial.materialCreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.material.pe.dentalflow.com/MaterialEndpoint/materialGetByIdRequest", ReplyAction="http://soap.material.pe.dentalflow.com/MaterialEndpoint/materialGetByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloMaterial.materialGetByIdResponse> materialGetByIdAsync(moduloMaterial.materialGetByIdRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.material.pe.dentalflow.com/")]
    public partial class material
    {
        
        private decimal costoUnitarioField;
        
        private bool costoUnitarioFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nombreField;
        
        private int stockField;
        
        private bool stockFieldSpecified;
        
        private int stockMinimoField;
        
        private bool stockMinimoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal costoUnitario
        {
            get
            {
                return this.costoUnitarioField;
            }
            set
            {
                this.costoUnitarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool costoUnitarioSpecified
        {
            get
            {
                return this.costoUnitarioFieldSpecified;
            }
            set
            {
                this.costoUnitarioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int stock
        {
            get
            {
                return this.stockField;
            }
            set
            {
                this.stockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockSpecified
        {
            get
            {
                return this.stockFieldSpecified;
            }
            set
            {
                this.stockFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int stockMinimo
        {
            get
            {
                return this.stockMinimoField;
            }
            set
            {
                this.stockMinimoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockMinimoSpecified
        {
            get
            {
                return this.stockMinimoFieldSpecified;
            }
            set
            {
                this.stockMinimoFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="materialGetAll", WrapperNamespace="http://soap.material.pe.dentalflow.com/", IsWrapped=true)]
    public partial class materialGetAllRequest
    {
        
        public materialGetAllRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="materialGetAllResponse", WrapperNamespace="http://soap.material.pe.dentalflow.com/", IsWrapped=true)]
    public partial class materialGetAllResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.material.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloMaterial.material[] @return;
        
        public materialGetAllResponse()
        {
        }
        
        public materialGetAllResponse(moduloMaterial.material[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="materialUpdate", WrapperNamespace="http://soap.material.pe.dentalflow.com/", IsWrapped=true)]
    public partial class materialUpdateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.material.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.material.pe.dentalflow.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.material.pe.dentalflow.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int stock;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.material.pe.dentalflow.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int stockMinimo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.material.pe.dentalflow.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal costoUnitario;
        
        public materialUpdateRequest()
        {
        }
        
        public materialUpdateRequest(int id, string nombre, int stock, int stockMinimo, decimal costoUnitario)
        {
            this.id = id;
            this.nombre = nombre;
            this.stock = stock;
            this.stockMinimo = stockMinimo;
            this.costoUnitario = costoUnitario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="materialUpdateResponse", WrapperNamespace="http://soap.material.pe.dentalflow.com/", IsWrapped=true)]
    public partial class materialUpdateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.material.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public materialUpdateResponse()
        {
        }
        
        public materialUpdateResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="materialDelete", WrapperNamespace="http://soap.material.pe.dentalflow.com/", IsWrapped=true)]
    public partial class materialDeleteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.material.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public materialDeleteRequest()
        {
        }
        
        public materialDeleteRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="materialDeleteResponse", WrapperNamespace="http://soap.material.pe.dentalflow.com/", IsWrapped=true)]
    public partial class materialDeleteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.material.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public materialDeleteResponse()
        {
        }
        
        public materialDeleteResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="stockCritico", WrapperNamespace="http://soap.material.pe.dentalflow.com/", IsWrapped=true)]
    public partial class stockCriticoRequest
    {
        
        public stockCriticoRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="stockCriticoResponse", WrapperNamespace="http://soap.material.pe.dentalflow.com/", IsWrapped=true)]
    public partial class stockCriticoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.material.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloMaterial.material[] @return;
        
        public stockCriticoResponse()
        {
        }
        
        public stockCriticoResponse(moduloMaterial.material[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="materialCreate", WrapperNamespace="http://soap.material.pe.dentalflow.com/", IsWrapped=true)]
    public partial class materialCreateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.material.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.material.pe.dentalflow.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int stock;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.material.pe.dentalflow.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int stockMinimo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.material.pe.dentalflow.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal costoUnitario;
        
        public materialCreateRequest()
        {
        }
        
        public materialCreateRequest(string nombre, int stock, int stockMinimo, decimal costoUnitario)
        {
            this.nombre = nombre;
            this.stock = stock;
            this.stockMinimo = stockMinimo;
            this.costoUnitario = costoUnitario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="materialCreateResponse", WrapperNamespace="http://soap.material.pe.dentalflow.com/", IsWrapped=true)]
    public partial class materialCreateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.material.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloMaterial.material @return;
        
        public materialCreateResponse()
        {
        }
        
        public materialCreateResponse(moduloMaterial.material @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="materialGetById", WrapperNamespace="http://soap.material.pe.dentalflow.com/", IsWrapped=true)]
    public partial class materialGetByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.material.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public materialGetByIdRequest()
        {
        }
        
        public materialGetByIdRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="materialGetByIdResponse", WrapperNamespace="http://soap.material.pe.dentalflow.com/", IsWrapped=true)]
    public partial class materialGetByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.material.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloMaterial.material @return;
        
        public materialGetByIdResponse()
        {
        }
        
        public materialGetByIdResponse(moduloMaterial.material @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface MaterialEndpointChannel : moduloMaterial.MaterialEndpoint, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class MaterialEndpointClient : System.ServiceModel.ClientBase<moduloMaterial.MaterialEndpoint>, moduloMaterial.MaterialEndpoint
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MaterialEndpointClient() : 
                base(MaterialEndpointClient.GetDefaultBinding(), MaterialEndpointClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MaterialEndpointPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MaterialEndpointClient(EndpointConfiguration endpointConfiguration) : 
                base(MaterialEndpointClient.GetBindingForEndpoint(endpointConfiguration), MaterialEndpointClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MaterialEndpointClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MaterialEndpointClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MaterialEndpointClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MaterialEndpointClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MaterialEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloMaterial.materialGetAllResponse> moduloMaterial.MaterialEndpoint.materialGetAllAsync(moduloMaterial.materialGetAllRequest request)
        {
            return base.Channel.materialGetAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloMaterial.materialGetAllResponse> materialGetAllAsync()
        {
            moduloMaterial.materialGetAllRequest inValue = new moduloMaterial.materialGetAllRequest();
            return ((moduloMaterial.MaterialEndpoint)(this)).materialGetAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloMaterial.materialUpdateResponse> moduloMaterial.MaterialEndpoint.materialUpdateAsync(moduloMaterial.materialUpdateRequest request)
        {
            return base.Channel.materialUpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloMaterial.materialUpdateResponse> materialUpdateAsync(int id, string nombre, int stock, int stockMinimo, decimal costoUnitario)
        {
            moduloMaterial.materialUpdateRequest inValue = new moduloMaterial.materialUpdateRequest();
            inValue.id = id;
            inValue.nombre = nombre;
            inValue.stock = stock;
            inValue.stockMinimo = stockMinimo;
            inValue.costoUnitario = costoUnitario;
            return ((moduloMaterial.MaterialEndpoint)(this)).materialUpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloMaterial.materialDeleteResponse> moduloMaterial.MaterialEndpoint.materialDeleteAsync(moduloMaterial.materialDeleteRequest request)
        {
            return base.Channel.materialDeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloMaterial.materialDeleteResponse> materialDeleteAsync(int id)
        {
            moduloMaterial.materialDeleteRequest inValue = new moduloMaterial.materialDeleteRequest();
            inValue.id = id;
            return ((moduloMaterial.MaterialEndpoint)(this)).materialDeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloMaterial.stockCriticoResponse> moduloMaterial.MaterialEndpoint.stockCriticoAsync(moduloMaterial.stockCriticoRequest request)
        {
            return base.Channel.stockCriticoAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloMaterial.stockCriticoResponse> stockCriticoAsync()
        {
            moduloMaterial.stockCriticoRequest inValue = new moduloMaterial.stockCriticoRequest();
            return ((moduloMaterial.MaterialEndpoint)(this)).stockCriticoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloMaterial.materialCreateResponse> moduloMaterial.MaterialEndpoint.materialCreateAsync(moduloMaterial.materialCreateRequest request)
        {
            return base.Channel.materialCreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloMaterial.materialCreateResponse> materialCreateAsync(string nombre, int stock, int stockMinimo, decimal costoUnitario)
        {
            moduloMaterial.materialCreateRequest inValue = new moduloMaterial.materialCreateRequest();
            inValue.nombre = nombre;
            inValue.stock = stock;
            inValue.stockMinimo = stockMinimo;
            inValue.costoUnitario = costoUnitario;
            return ((moduloMaterial.MaterialEndpoint)(this)).materialCreateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloMaterial.materialGetByIdResponse> moduloMaterial.MaterialEndpoint.materialGetByIdAsync(moduloMaterial.materialGetByIdRequest request)
        {
            return base.Channel.materialGetByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloMaterial.materialGetByIdResponse> materialGetByIdAsync(int id)
        {
            moduloMaterial.materialGetByIdRequest inValue = new moduloMaterial.materialGetByIdRequest();
            inValue.id = id;
            return ((moduloMaterial.MaterialEndpoint)(this)).materialGetByIdAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MaterialEndpointPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MaterialEndpointPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:1520/ws/Material");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MaterialEndpointClient.GetBindingForEndpoint(EndpointConfiguration.MaterialEndpointPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MaterialEndpointClient.GetEndpointAddress(EndpointConfiguration.MaterialEndpointPort);
        }
        
        public enum EndpointConfiguration
        {
            
            MaterialEndpointPort,
        }
    }
}
