//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moduloDashboard
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://serviceImpl.dashboard.pe.dentalflow.com/", ConfigurationName="moduloDashboard.DashboardServiceImpl")]
    public interface DashboardServiceImpl
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviceImpl.dashboard.pe.dentalflow.com/DashboardServiceImpl/obtenerMetric" +
            "asRequest", ReplyAction="http://serviceImpl.dashboard.pe.dentalflow.com/DashboardServiceImpl/obtenerMetric" +
            "asResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloDashboard.obtenerMetricasResponse> obtenerMetricasAsync(moduloDashboard.obtenerMetricasRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceImpl.dashboard.pe.dentalflow.com/")]
    public partial class dashboard
    {
        
        private long citasDelDiaField;
        
        private bool citasDelDiaFieldSpecified;
        
        private long pagosRealizadosField;
        
        private bool pagosRealizadosFieldSpecified;
        
        private long stockCriticoField;
        
        private bool stockCriticoFieldSpecified;
        
        private long tratamientosActivosField;
        
        private bool tratamientosActivosFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long citasDelDia
        {
            get
            {
                return this.citasDelDiaField;
            }
            set
            {
                this.citasDelDiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool citasDelDiaSpecified
        {
            get
            {
                return this.citasDelDiaFieldSpecified;
            }
            set
            {
                this.citasDelDiaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long pagosRealizados
        {
            get
            {
                return this.pagosRealizadosField;
            }
            set
            {
                this.pagosRealizadosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pagosRealizadosSpecified
        {
            get
            {
                return this.pagosRealizadosFieldSpecified;
            }
            set
            {
                this.pagosRealizadosFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long stockCritico
        {
            get
            {
                return this.stockCriticoField;
            }
            set
            {
                this.stockCriticoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockCriticoSpecified
        {
            get
            {
                return this.stockCriticoFieldSpecified;
            }
            set
            {
                this.stockCriticoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long tratamientosActivos
        {
            get
            {
                return this.tratamientosActivosField;
            }
            set
            {
                this.tratamientosActivosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tratamientosActivosSpecified
        {
            get
            {
                return this.tratamientosActivosFieldSpecified;
            }
            set
            {
                this.tratamientosActivosFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerMetricas", WrapperNamespace="http://serviceImpl.dashboard.pe.dentalflow.com/", IsWrapped=true)]
    public partial class obtenerMetricasRequest
    {
        
        public obtenerMetricasRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerMetricasResponse", WrapperNamespace="http://serviceImpl.dashboard.pe.dentalflow.com/", IsWrapped=true)]
    public partial class obtenerMetricasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviceImpl.dashboard.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloDashboard.dashboard @return;
        
        public obtenerMetricasResponse()
        {
        }
        
        public obtenerMetricasResponse(moduloDashboard.dashboard @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface DashboardServiceImplChannel : moduloDashboard.DashboardServiceImpl, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class DashboardServiceImplClient : System.ServiceModel.ClientBase<moduloDashboard.DashboardServiceImpl>, moduloDashboard.DashboardServiceImpl
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DashboardServiceImplClient() : 
                base(DashboardServiceImplClient.GetDefaultBinding(), DashboardServiceImplClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DashboardServiceImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DashboardServiceImplClient(EndpointConfiguration endpointConfiguration) : 
                base(DashboardServiceImplClient.GetBindingForEndpoint(endpointConfiguration), DashboardServiceImplClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DashboardServiceImplClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DashboardServiceImplClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DashboardServiceImplClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DashboardServiceImplClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DashboardServiceImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloDashboard.obtenerMetricasResponse> moduloDashboard.DashboardServiceImpl.obtenerMetricasAsync(moduloDashboard.obtenerMetricasRequest request)
        {
            return base.Channel.obtenerMetricasAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloDashboard.obtenerMetricasResponse> obtenerMetricasAsync()
        {
            moduloDashboard.obtenerMetricasRequest inValue = new moduloDashboard.obtenerMetricasRequest();
            return ((moduloDashboard.DashboardServiceImpl)(this)).obtenerMetricasAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DashboardServiceImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DashboardServiceImplPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:1520/ws/Dashboard");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DashboardServiceImplClient.GetBindingForEndpoint(EndpointConfiguration.DashboardServiceImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DashboardServiceImplClient.GetEndpointAddress(EndpointConfiguration.DashboardServiceImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            DashboardServiceImplPort,
        }
    }
}
