//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moduloDashboard
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap.dashboard.pe.dentalflow.com/", ConfigurationName="moduloDashboard.DashboardEndpoint")]
    public interface DashboardEndpoint
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.dashboard.pe.dentalflow.com/DashboardEndpoint/obtenerPagosTotalesUlti" +
            "mos5MesesRequest", ReplyAction="http://soap.dashboard.pe.dentalflow.com/DashboardEndpoint/obtenerPagosTotalesUlti" +
            "mos5MesesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloDashboard.obtenerPagosTotalesUltimos5MesesResponse> obtenerPagosTotalesUltimos5MesesAsync(moduloDashboard.obtenerPagosTotalesUltimos5MesesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.dashboard.pe.dentalflow.com/DashboardEndpoint/obtenerMetricasRequest", ReplyAction="http://soap.dashboard.pe.dentalflow.com/DashboardEndpoint/obtenerMetricasResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloDashboard.obtenerMetricasResponse> obtenerMetricasAsync(moduloDashboard.obtenerMetricasRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.dashboard.pe.dentalflow.com/")]
    public partial class pagoTotalMesDto
    {
        
        private int anioField;
        
        private int mesField;
        
        private decimal totalPagoField;
        
        private bool totalPagoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int anio
        {
            get
            {
                return this.anioField;
            }
            set
            {
                this.anioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int mes
        {
            get
            {
                return this.mesField;
            }
            set
            {
                this.mesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal totalPago
        {
            get
            {
                return this.totalPagoField;
            }
            set
            {
                this.totalPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalPagoSpecified
        {
            get
            {
                return this.totalPagoFieldSpecified;
            }
            set
            {
                this.totalPagoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.dashboard.pe.dentalflow.com/")]
    public partial class dashboard
    {
        
        private long citasDelDiaField;
        
        private bool citasDelDiaFieldSpecified;
        
        private long pagosRealizadosField;
        
        private bool pagosRealizadosFieldSpecified;
        
        private long stockCriticoField;
        
        private bool stockCriticoFieldSpecified;
        
        private long tratamientosActivosField;
        
        private bool tratamientosActivosFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long citasDelDia
        {
            get
            {
                return this.citasDelDiaField;
            }
            set
            {
                this.citasDelDiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool citasDelDiaSpecified
        {
            get
            {
                return this.citasDelDiaFieldSpecified;
            }
            set
            {
                this.citasDelDiaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long pagosRealizados
        {
            get
            {
                return this.pagosRealizadosField;
            }
            set
            {
                this.pagosRealizadosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pagosRealizadosSpecified
        {
            get
            {
                return this.pagosRealizadosFieldSpecified;
            }
            set
            {
                this.pagosRealizadosFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long stockCritico
        {
            get
            {
                return this.stockCriticoField;
            }
            set
            {
                this.stockCriticoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockCriticoSpecified
        {
            get
            {
                return this.stockCriticoFieldSpecified;
            }
            set
            {
                this.stockCriticoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long tratamientosActivos
        {
            get
            {
                return this.tratamientosActivosField;
            }
            set
            {
                this.tratamientosActivosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tratamientosActivosSpecified
        {
            get
            {
                return this.tratamientosActivosFieldSpecified;
            }
            set
            {
                this.tratamientosActivosFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPagosTotalesUltimos5Meses", WrapperNamespace="http://soap.dashboard.pe.dentalflow.com/", IsWrapped=true)]
    public partial class obtenerPagosTotalesUltimos5MesesRequest
    {
        
        public obtenerPagosTotalesUltimos5MesesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPagosTotalesUltimos5MesesResponse", WrapperNamespace="http://soap.dashboard.pe.dentalflow.com/", IsWrapped=true)]
    public partial class obtenerPagosTotalesUltimos5MesesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.dashboard.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloDashboard.pagoTotalMesDto[] @return;
        
        public obtenerPagosTotalesUltimos5MesesResponse()
        {
        }
        
        public obtenerPagosTotalesUltimos5MesesResponse(moduloDashboard.pagoTotalMesDto[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerMetricas", WrapperNamespace="http://soap.dashboard.pe.dentalflow.com/", IsWrapped=true)]
    public partial class obtenerMetricasRequest
    {
        
        public obtenerMetricasRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerMetricasResponse", WrapperNamespace="http://soap.dashboard.pe.dentalflow.com/", IsWrapped=true)]
    public partial class obtenerMetricasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.dashboard.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloDashboard.dashboard @return;
        
        public obtenerMetricasResponse()
        {
        }
        
        public obtenerMetricasResponse(moduloDashboard.dashboard @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface DashboardEndpointChannel : moduloDashboard.DashboardEndpoint, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class DashboardEndpointClient : System.ServiceModel.ClientBase<moduloDashboard.DashboardEndpoint>, moduloDashboard.DashboardEndpoint
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DashboardEndpointClient() : 
                base(DashboardEndpointClient.GetDefaultBinding(), DashboardEndpointClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DashboardEndpointPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DashboardEndpointClient(EndpointConfiguration endpointConfiguration) : 
                base(DashboardEndpointClient.GetBindingForEndpoint(endpointConfiguration), DashboardEndpointClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DashboardEndpointClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DashboardEndpointClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DashboardEndpointClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DashboardEndpointClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DashboardEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloDashboard.obtenerPagosTotalesUltimos5MesesResponse> moduloDashboard.DashboardEndpoint.obtenerPagosTotalesUltimos5MesesAsync(moduloDashboard.obtenerPagosTotalesUltimos5MesesRequest request)
        {
            return base.Channel.obtenerPagosTotalesUltimos5MesesAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloDashboard.obtenerPagosTotalesUltimos5MesesResponse> obtenerPagosTotalesUltimos5MesesAsync()
        {
            moduloDashboard.obtenerPagosTotalesUltimos5MesesRequest inValue = new moduloDashboard.obtenerPagosTotalesUltimos5MesesRequest();
            return ((moduloDashboard.DashboardEndpoint)(this)).obtenerPagosTotalesUltimos5MesesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloDashboard.obtenerMetricasResponse> moduloDashboard.DashboardEndpoint.obtenerMetricasAsync(moduloDashboard.obtenerMetricasRequest request)
        {
            return base.Channel.obtenerMetricasAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloDashboard.obtenerMetricasResponse> obtenerMetricasAsync()
        {
            moduloDashboard.obtenerMetricasRequest inValue = new moduloDashboard.obtenerMetricasRequest();
            return ((moduloDashboard.DashboardEndpoint)(this)).obtenerMetricasAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DashboardEndpointPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DashboardEndpointPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:1520/ws/Dashboard");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DashboardEndpointClient.GetBindingForEndpoint(EndpointConfiguration.DashboardEndpointPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DashboardEndpointClient.GetEndpointAddress(EndpointConfiguration.DashboardEndpointPort);
        }
        
        public enum EndpointConfiguration
        {
            
            DashboardEndpointPort,
        }
    }
}
