//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moduloPago
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://impl.service.payment.pe.dentalflow.com/", ConfigurationName="moduloPago.PagoServiceImpl")]
    public interface PagoServiceImpl
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://impl.service.payment.pe.dentalflow.com/PagoServiceImpl/registerPagoCitaReq" +
            "uest", ReplyAction="http://impl.service.payment.pe.dentalflow.com/PagoServiceImpl/registerPagoCitaRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloPago.registerPagoCitaResponse> registerPagoCitaAsync(moduloPago.registerPagoCitaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://impl.service.payment.pe.dentalflow.com/PagoServiceImpl/findPagoByIdRequest" +
            "", ReplyAction="http://impl.service.payment.pe.dentalflow.com/PagoServiceImpl/findPagoByIdRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloPago.findPagoByIdResponse> findPagoByIdAsync(moduloPago.findPagoByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://impl.service.payment.pe.dentalflow.com/PagoServiceImpl/registerPagoTratami" +
            "entoRequest", ReplyAction="http://impl.service.payment.pe.dentalflow.com/PagoServiceImpl/registerPagoTratami" +
            "entoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloPago.registerPagoTratamientoResponse> registerPagoTratamientoAsync(moduloPago.registerPagoTratamientoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.service.payment.pe.dentalflow.com/")]
    public partial class pagoRequestDto
    {
        
        private string metodoPagoField;
        
        private decimal montoField;
        
        private bool montoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string metodoPago
        {
            get
            {
                return this.metodoPagoField;
            }
            set
            {
                this.metodoPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal monto
        {
            get
            {
                return this.montoField;
            }
            set
            {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool montoSpecified
        {
            get
            {
                return this.montoFieldSpecified;
            }
            set
            {
                this.montoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.service.payment.pe.dentalflow.com/")]
    public partial class pagoResponseDto
    {
        
        private int idPagoField;
        
        private string razonField;
        
        private string nombresPacienteField;
        
        private string apellidosPacienteField;
        
        private string nombreEspecialidadField;
        
        private decimal montoField;
        
        private bool montoFieldSpecified;
        
        private string fechaField;
        
        private string metodoPagoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idPago
        {
            get
            {
                return this.idPagoField;
            }
            set
            {
                this.idPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string razon
        {
            get
            {
                return this.razonField;
            }
            set
            {
                this.razonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombresPaciente
        {
            get
            {
                return this.nombresPacienteField;
            }
            set
            {
                this.nombresPacienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string apellidosPaciente
        {
            get
            {
                return this.apellidosPacienteField;
            }
            set
            {
                this.apellidosPacienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombreEspecialidad
        {
            get
            {
                return this.nombreEspecialidadField;
            }
            set
            {
                this.nombreEspecialidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal monto
        {
            get
            {
                return this.montoField;
            }
            set
            {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool montoSpecified
        {
            get
            {
                return this.montoFieldSpecified;
            }
            set
            {
                this.montoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string metodoPago
        {
            get
            {
                return this.metodoPagoField;
            }
            set
            {
                this.metodoPagoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerPagoCita", WrapperNamespace="http://impl.service.payment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class registerPagoCitaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.payment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloPago.pagoRequestDto arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.payment.pe.dentalflow.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public registerPagoCitaRequest()
        {
        }
        
        public registerPagoCitaRequest(moduloPago.pagoRequestDto arg0, int arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerPagoCitaResponse", WrapperNamespace="http://impl.service.payment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class registerPagoCitaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.payment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloPago.pagoResponseDto @return;
        
        public registerPagoCitaResponse()
        {
        }
        
        public registerPagoCitaResponse(moduloPago.pagoResponseDto @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findPagoById", WrapperNamespace="http://impl.service.payment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class findPagoByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.payment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public findPagoByIdRequest()
        {
        }
        
        public findPagoByIdRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findPagoByIdResponse", WrapperNamespace="http://impl.service.payment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class findPagoByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.payment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloPago.pagoResponseDto @return;
        
        public findPagoByIdResponse()
        {
        }
        
        public findPagoByIdResponse(moduloPago.pagoResponseDto @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerPagoTratamiento", WrapperNamespace="http://impl.service.payment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class registerPagoTratamientoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.payment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloPago.pagoRequestDto arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.payment.pe.dentalflow.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public registerPagoTratamientoRequest()
        {
        }
        
        public registerPagoTratamientoRequest(moduloPago.pagoRequestDto arg0, int arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerPagoTratamientoResponse", WrapperNamespace="http://impl.service.payment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class registerPagoTratamientoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.service.payment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloPago.pagoResponseDto @return;
        
        public registerPagoTratamientoResponse()
        {
        }
        
        public registerPagoTratamientoResponse(moduloPago.pagoResponseDto @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface PagoServiceImplChannel : moduloPago.PagoServiceImpl, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class PagoServiceImplClient : System.ServiceModel.ClientBase<moduloPago.PagoServiceImpl>, moduloPago.PagoServiceImpl
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PagoServiceImplClient() : 
                base(PagoServiceImplClient.GetDefaultBinding(), PagoServiceImplClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PagoServiceImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PagoServiceImplClient(EndpointConfiguration endpointConfiguration) : 
                base(PagoServiceImplClient.GetBindingForEndpoint(endpointConfiguration), PagoServiceImplClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PagoServiceImplClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PagoServiceImplClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PagoServiceImplClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PagoServiceImplClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PagoServiceImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloPago.registerPagoCitaResponse> moduloPago.PagoServiceImpl.registerPagoCitaAsync(moduloPago.registerPagoCitaRequest request)
        {
            return base.Channel.registerPagoCitaAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloPago.registerPagoCitaResponse> registerPagoCitaAsync(moduloPago.pagoRequestDto arg0, int arg1)
        {
            moduloPago.registerPagoCitaRequest inValue = new moduloPago.registerPagoCitaRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((moduloPago.PagoServiceImpl)(this)).registerPagoCitaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloPago.findPagoByIdResponse> moduloPago.PagoServiceImpl.findPagoByIdAsync(moduloPago.findPagoByIdRequest request)
        {
            return base.Channel.findPagoByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloPago.findPagoByIdResponse> findPagoByIdAsync(int arg0)
        {
            moduloPago.findPagoByIdRequest inValue = new moduloPago.findPagoByIdRequest();
            inValue.arg0 = arg0;
            return ((moduloPago.PagoServiceImpl)(this)).findPagoByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloPago.registerPagoTratamientoResponse> moduloPago.PagoServiceImpl.registerPagoTratamientoAsync(moduloPago.registerPagoTratamientoRequest request)
        {
            return base.Channel.registerPagoTratamientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloPago.registerPagoTratamientoResponse> registerPagoTratamientoAsync(moduloPago.pagoRequestDto arg0, int arg1)
        {
            moduloPago.registerPagoTratamientoRequest inValue = new moduloPago.registerPagoTratamientoRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((moduloPago.PagoServiceImpl)(this)).registerPagoTratamientoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PagoServiceImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PagoServiceImplPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:1520/ws/Pago");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PagoServiceImplClient.GetBindingForEndpoint(EndpointConfiguration.PagoServiceImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PagoServiceImplClient.GetEndpointAddress(EndpointConfiguration.PagoServiceImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            PagoServiceImplPort,
        }
    }
}
