//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moduloCitas
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.appointment.pe.dentalflow.com/", ConfigurationName="moduloCitas.AppointmentService")]
    public interface AppointmentService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.appointment.pe.dentalflow.com/AppointmentService/createAppointment" +
            "Request", ReplyAction="http://service.appointment.pe.dentalflow.com/AppointmentService/createAppointment" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloCitas.createAppointmentResponse> createAppointmentAsync(moduloCitas.createAppointmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.appointment.pe.dentalflow.com/AppointmentService/cancelAppointment" +
            "Request", ReplyAction="http://service.appointment.pe.dentalflow.com/AppointmentService/cancelAppointment" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloCitas.cancelAppointmentResponse> cancelAppointmentAsync(moduloCitas.cancelAppointmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.appointment.pe.dentalflow.com/AppointmentService/getAllAppointment" +
            "sRequest", ReplyAction="http://service.appointment.pe.dentalflow.com/AppointmentService/getAllAppointment" +
            "sResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloCitas.getAllAppointmentsResponse> getAllAppointmentsAsync(moduloCitas.getAllAppointmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.appointment.pe.dentalflow.com/AppointmentService/getAppointmentByI" +
            "dRequest", ReplyAction="http://service.appointment.pe.dentalflow.com/AppointmentService/getAppointmentByI" +
            "dResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloCitas.getAppointmentByIdResponse> getAppointmentByIdAsync(moduloCitas.getAppointmentByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.appointment.pe.dentalflow.com/AppointmentService/rescheduleAppoint" +
            "mentRequest", ReplyAction="http://service.appointment.pe.dentalflow.com/AppointmentService/rescheduleAppoint" +
            "mentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloCitas.rescheduleAppointmentResponse> rescheduleAppointmentAsync(moduloCitas.rescheduleAppointmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.appointment.pe.dentalflow.com/AppointmentService/getAppointmentsBy" +
            "PatientRequest", ReplyAction="http://service.appointment.pe.dentalflow.com/AppointmentService/getAppointmentsBy" +
            "PatientResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloCitas.getAppointmentsByPatientResponse> getAppointmentsByPatientAsync(moduloCitas.getAppointmentsByPatientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.appointment.pe.dentalflow.com/AppointmentService/getAppointmentsBy" +
            "DentistRequest", ReplyAction="http://service.appointment.pe.dentalflow.com/AppointmentService/getAppointmentsBy" +
            "DentistResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<moduloCitas.getAppointmentsByDentistResponse> getAppointmentsByDentistAsync(moduloCitas.getAppointmentsByDentistRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.appointment.pe.dentalflow.com/")]
    public partial class appointment
    {
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private localDate appointmentDateField;
        
        private appointmentType appointmentTypeField;
        
        private localDateTime createdAtField;
        
        private clinicalStaff dentistField;
        
        private localTime endTimeField;
        
        private int idField;
        
        private patient patientField;
        
        private string reasonField;
        
        private localTime startTimeField;
        
        private appointmentStatus statusField;
        
        private bool statusFieldSpecified;
        
        private localDateTime updatedAtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified
        {
            get
            {
                return this.amountFieldSpecified;
            }
            set
            {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public localDate appointmentDate
        {
            get
            {
                return this.appointmentDateField;
            }
            set
            {
                this.appointmentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public appointmentType appointmentType
        {
            get
            {
                return this.appointmentTypeField;
            }
            set
            {
                this.appointmentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDateTime createdAt
        {
            get
            {
                return this.createdAtField;
            }
            set
            {
                this.createdAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public clinicalStaff dentist
        {
            get
            {
                return this.dentistField;
            }
            set
            {
                this.dentistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public localTime endTime
        {
            get
            {
                return this.endTimeField;
            }
            set
            {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public patient patient
        {
            get
            {
                return this.patientField;
            }
            set
            {
                this.patientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string reason
        {
            get
            {
                return this.reasonField;
            }
            set
            {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public localTime startTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public appointmentStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public localDateTime updatedAt
        {
            get
            {
                return this.updatedAtField;
            }
            set
            {
                this.updatedAtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.appointment.pe.dentalflow.com/")]
    public partial class localDate
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.appointment.pe.dentalflow.com/")]
    public partial class patient
    {
        
        private string addressField;
        
        private localDate birthDateField;
        
        private localDateTime createdAtField;
        
        private string dniField;
        
        private string emailField;
        
        private string firstNameField;
        
        private string genderField;
        
        private int idField;
        
        private string lastNameField;
        
        private string phoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public localDate birthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public localDateTime createdAt
        {
            get
            {
                return this.createdAtField;
            }
            set
            {
                this.createdAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string dni
        {
            get
            {
                return this.dniField;
            }
            set
            {
                this.dniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.appointment.pe.dentalflow.com/")]
    public partial class localDateTime
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.appointment.pe.dentalflow.com/")]
    public partial class localTime
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.appointment.pe.dentalflow.com/")]
    public partial class rol
    {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.appointment.pe.dentalflow.com/")]
    public partial class usuario
    {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string passwordField;
        
        private rol rolField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo
        {
            get
            {
                return this.activoField;
            }
            set
            {
                this.activoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified
        {
            get
            {
                return this.activoFieldSpecified;
            }
            set
            {
                this.activoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public rol rol
        {
            get
            {
                return this.rolField;
            }
            set
            {
                this.rolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.appointment.pe.dentalflow.com/")]
    public partial class specialty
    {
        
        private localDateTime createdAtField;
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public localDateTime createdAt
        {
            get
            {
                return this.createdAtField;
            }
            set
            {
                this.createdAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.appointment.pe.dentalflow.com/")]
    public partial class clinicalStaff
    {
        
        private localDateTime createdAtField;
        
        private bool disponibleField;
        
        private bool disponibleFieldSpecified;
        
        private string firstNameField;
        
        private int idField;
        
        private string lastNameField;
        
        private string licenseNumberField;
        
        private string phoneField;
        
        private specialty specialtyField;
        
        private usuario usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public localDateTime createdAt
        {
            get
            {
                return this.createdAtField;
            }
            set
            {
                this.createdAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool disponible
        {
            get
            {
                return this.disponibleField;
            }
            set
            {
                this.disponibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool disponibleSpecified
        {
            get
            {
                return this.disponibleFieldSpecified;
            }
            set
            {
                this.disponibleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string licenseNumber
        {
            get
            {
                return this.licenseNumberField;
            }
            set
            {
                this.licenseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public specialty specialty
        {
            get
            {
                return this.specialtyField;
            }
            set
            {
                this.specialtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public usuario usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.appointment.pe.dentalflow.com/")]
    public partial class appointmentType
    {
        
        private localDateTime createdAtField;
        
        private int durationMinutesField;
        
        private bool durationMinutesFieldSpecified;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public localDateTime createdAt
        {
            get
            {
                return this.createdAtField;
            }
            set
            {
                this.createdAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int durationMinutes
        {
            get
            {
                return this.durationMinutesField;
            }
            set
            {
                this.durationMinutesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool durationMinutesSpecified
        {
            get
            {
                return this.durationMinutesFieldSpecified;
            }
            set
            {
                this.durationMinutesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.appointment.pe.dentalflow.com/")]
    public enum appointmentStatus
    {
        
        /// <remarks/>
        PENDING,
        
        /// <remarks/>
        CONFIRMED,
        
        /// <remarks/>
        CANCELLED,
        
        /// <remarks/>
        COMPLETED,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createAppointment", WrapperNamespace="http://service.appointment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class createAppointmentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.appointment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.appointment.pe.dentalflow.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.appointment.pe.dentalflow.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.appointment.pe.dentalflow.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.appointment.pe.dentalflow.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.appointment.pe.dentalflow.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg5;
        
        public createAppointmentRequest()
        {
        }
        
        public createAppointmentRequest(int arg0, int arg1, long arg2, string arg3, string arg4, string arg5)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createAppointmentResponse", WrapperNamespace="http://service.appointment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class createAppointmentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.appointment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloCitas.appointment @return;
        
        public createAppointmentResponse()
        {
        }
        
        public createAppointmentResponse(moduloCitas.appointment @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelAppointment", WrapperNamespace="http://service.appointment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class cancelAppointmentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.appointment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public cancelAppointmentRequest()
        {
        }
        
        public cancelAppointmentRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelAppointmentResponse", WrapperNamespace="http://service.appointment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class cancelAppointmentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.appointment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloCitas.appointment @return;
        
        public cancelAppointmentResponse()
        {
        }
        
        public cancelAppointmentResponse(moduloCitas.appointment @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllAppointments", WrapperNamespace="http://service.appointment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getAllAppointmentsRequest
    {
        
        public getAllAppointmentsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllAppointmentsResponse", WrapperNamespace="http://service.appointment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getAllAppointmentsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.appointment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloCitas.appointment[] @return;
        
        public getAllAppointmentsResponse()
        {
        }
        
        public getAllAppointmentsResponse(moduloCitas.appointment[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAppointmentById", WrapperNamespace="http://service.appointment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getAppointmentByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.appointment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getAppointmentByIdRequest()
        {
        }
        
        public getAppointmentByIdRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAppointmentByIdResponse", WrapperNamespace="http://service.appointment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getAppointmentByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.appointment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloCitas.appointment @return;
        
        public getAppointmentByIdResponse()
        {
        }
        
        public getAppointmentByIdResponse(moduloCitas.appointment @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rescheduleAppointment", WrapperNamespace="http://service.appointment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class rescheduleAppointmentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.appointment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.appointment.pe.dentalflow.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.appointment.pe.dentalflow.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public rescheduleAppointmentRequest()
        {
        }
        
        public rescheduleAppointmentRequest(int arg0, string arg1, string arg2)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rescheduleAppointmentResponse", WrapperNamespace="http://service.appointment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class rescheduleAppointmentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.appointment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloCitas.appointment @return;
        
        public rescheduleAppointmentResponse()
        {
        }
        
        public rescheduleAppointmentResponse(moduloCitas.appointment @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAppointmentsByPatient", WrapperNamespace="http://service.appointment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getAppointmentsByPatientRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.appointment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getAppointmentsByPatientRequest()
        {
        }
        
        public getAppointmentsByPatientRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAppointmentsByPatientResponse", WrapperNamespace="http://service.appointment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getAppointmentsByPatientResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.appointment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloCitas.appointment[] @return;
        
        public getAppointmentsByPatientResponse()
        {
        }
        
        public getAppointmentsByPatientResponse(moduloCitas.appointment[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAppointmentsByDentist", WrapperNamespace="http://service.appointment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getAppointmentsByDentistRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.appointment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getAppointmentsByDentistRequest()
        {
        }
        
        public getAppointmentsByDentistRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAppointmentsByDentistResponse", WrapperNamespace="http://service.appointment.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getAppointmentsByDentistResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.appointment.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public moduloCitas.appointment[] @return;
        
        public getAppointmentsByDentistResponse()
        {
        }
        
        public getAppointmentsByDentistResponse(moduloCitas.appointment[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface AppointmentServiceChannel : moduloCitas.AppointmentService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class AppointmentServiceClient : System.ServiceModel.ClientBase<moduloCitas.AppointmentService>, moduloCitas.AppointmentService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AppointmentServiceClient() : 
                base(AppointmentServiceClient.GetDefaultBinding(), AppointmentServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AppointmentServiceImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppointmentServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(AppointmentServiceClient.GetBindingForEndpoint(endpointConfiguration), AppointmentServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppointmentServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AppointmentServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppointmentServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AppointmentServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AppointmentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloCitas.createAppointmentResponse> moduloCitas.AppointmentService.createAppointmentAsync(moduloCitas.createAppointmentRequest request)
        {
            return base.Channel.createAppointmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloCitas.createAppointmentResponse> createAppointmentAsync(int arg0, int arg1, long arg2, string arg3, string arg4, string arg5)
        {
            moduloCitas.createAppointmentRequest inValue = new moduloCitas.createAppointmentRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            return ((moduloCitas.AppointmentService)(this)).createAppointmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloCitas.cancelAppointmentResponse> moduloCitas.AppointmentService.cancelAppointmentAsync(moduloCitas.cancelAppointmentRequest request)
        {
            return base.Channel.cancelAppointmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloCitas.cancelAppointmentResponse> cancelAppointmentAsync(int arg0)
        {
            moduloCitas.cancelAppointmentRequest inValue = new moduloCitas.cancelAppointmentRequest();
            inValue.arg0 = arg0;
            return ((moduloCitas.AppointmentService)(this)).cancelAppointmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloCitas.getAllAppointmentsResponse> moduloCitas.AppointmentService.getAllAppointmentsAsync(moduloCitas.getAllAppointmentsRequest request)
        {
            return base.Channel.getAllAppointmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloCitas.getAllAppointmentsResponse> getAllAppointmentsAsync()
        {
            moduloCitas.getAllAppointmentsRequest inValue = new moduloCitas.getAllAppointmentsRequest();
            return ((moduloCitas.AppointmentService)(this)).getAllAppointmentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloCitas.getAppointmentByIdResponse> moduloCitas.AppointmentService.getAppointmentByIdAsync(moduloCitas.getAppointmentByIdRequest request)
        {
            return base.Channel.getAppointmentByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloCitas.getAppointmentByIdResponse> getAppointmentByIdAsync(int arg0)
        {
            moduloCitas.getAppointmentByIdRequest inValue = new moduloCitas.getAppointmentByIdRequest();
            inValue.arg0 = arg0;
            return ((moduloCitas.AppointmentService)(this)).getAppointmentByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloCitas.rescheduleAppointmentResponse> moduloCitas.AppointmentService.rescheduleAppointmentAsync(moduloCitas.rescheduleAppointmentRequest request)
        {
            return base.Channel.rescheduleAppointmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloCitas.rescheduleAppointmentResponse> rescheduleAppointmentAsync(int arg0, string arg1, string arg2)
        {
            moduloCitas.rescheduleAppointmentRequest inValue = new moduloCitas.rescheduleAppointmentRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((moduloCitas.AppointmentService)(this)).rescheduleAppointmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloCitas.getAppointmentsByPatientResponse> moduloCitas.AppointmentService.getAppointmentsByPatientAsync(moduloCitas.getAppointmentsByPatientRequest request)
        {
            return base.Channel.getAppointmentsByPatientAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloCitas.getAppointmentsByPatientResponse> getAppointmentsByPatientAsync(int arg0)
        {
            moduloCitas.getAppointmentsByPatientRequest inValue = new moduloCitas.getAppointmentsByPatientRequest();
            inValue.arg0 = arg0;
            return ((moduloCitas.AppointmentService)(this)).getAppointmentsByPatientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<moduloCitas.getAppointmentsByDentistResponse> moduloCitas.AppointmentService.getAppointmentsByDentistAsync(moduloCitas.getAppointmentsByDentistRequest request)
        {
            return base.Channel.getAppointmentsByDentistAsync(request);
        }
        
        public System.Threading.Tasks.Task<moduloCitas.getAppointmentsByDentistResponse> getAppointmentsByDentistAsync(int arg0)
        {
            moduloCitas.getAppointmentsByDentistRequest inValue = new moduloCitas.getAppointmentsByDentistRequest();
            inValue.arg0 = arg0;
            return ((moduloCitas.AppointmentService)(this)).getAppointmentsByDentistAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AppointmentServiceImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AppointmentServiceImplPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:1520/ws/Appointment");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AppointmentServiceClient.GetBindingForEndpoint(EndpointConfiguration.AppointmentServiceImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AppointmentServiceClient.GetEndpointAddress(EndpointConfiguration.AppointmentServiceImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            AppointmentServiceImplPort,
        }
    }
}
