//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicioAuth
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap.auth.pe.dentalflow.com/", ConfigurationName="servicioAuth.AuthEndpoint")]
    public interface AuthEndpoint
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.auth.pe.dentalflow.com/AuthEndpoint/loginRequest", ReplyAction="http://soap.auth.pe.dentalflow.com/AuthEndpoint/loginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<servicioAuth.loginResponse> loginAsync(servicioAuth.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.auth.pe.dentalflow.com/AuthEndpoint/disableUserRequest", ReplyAction="http://soap.auth.pe.dentalflow.com/AuthEndpoint/disableUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<servicioAuth.disableUserResponse> disableUserAsync(servicioAuth.disableUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.auth.pe.dentalflow.com/AuthEndpoint/getAllUsersRequest", ReplyAction="http://soap.auth.pe.dentalflow.com/AuthEndpoint/getAllUsersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<servicioAuth.getAllUsersResponse> getAllUsersAsync(servicioAuth.getAllUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.auth.pe.dentalflow.com/AuthEndpoint/createUserRequest", ReplyAction="http://soap.auth.pe.dentalflow.com/AuthEndpoint/createUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<servicioAuth.createUserResponse> createUserAsync(servicioAuth.createUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.auth.pe.dentalflow.com/AuthEndpoint/updateUserRequest", ReplyAction="http://soap.auth.pe.dentalflow.com/AuthEndpoint/updateUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<servicioAuth.updateUserResponse> updateUserAsync(servicioAuth.updateUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="login", WrapperNamespace="http://soap.auth.pe.dentalflow.com/", IsWrapped=true)]
    public partial class loginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.auth.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.auth.pe.dentalflow.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public loginRequest()
        {
        }
        
        public loginRequest(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginResponse", WrapperNamespace="http://soap.auth.pe.dentalflow.com/", IsWrapped=true)]
    public partial class loginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.auth.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public loginResponse()
        {
        }
        
        public loginResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.auth.pe.dentalflow.com/")]
    public partial class usuario
    {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string passwordField;
        
        private rol rolField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo
        {
            get
            {
                return this.activoField;
            }
            set
            {
                this.activoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified
        {
            get
            {
                return this.activoFieldSpecified;
            }
            set
            {
                this.activoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public rol rol
        {
            get
            {
                return this.rolField;
            }
            set
            {
                this.rolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.auth.pe.dentalflow.com/")]
    public partial class rol
    {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="disableUser", WrapperNamespace="http://soap.auth.pe.dentalflow.com/", IsWrapped=true)]
    public partial class disableUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.auth.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int userId;
        
        public disableUserRequest()
        {
        }
        
        public disableUserRequest(int userId)
        {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="disableUserResponse", WrapperNamespace="http://soap.auth.pe.dentalflow.com/", IsWrapped=true)]
    public partial class disableUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.auth.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public servicioAuth.usuario @return;
        
        public disableUserResponse()
        {
        }
        
        public disableUserResponse(servicioAuth.usuario @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllUsers", WrapperNamespace="http://soap.auth.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getAllUsersRequest
    {
        
        public getAllUsersRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllUsersResponse", WrapperNamespace="http://soap.auth.pe.dentalflow.com/", IsWrapped=true)]
    public partial class getAllUsersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.auth.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public servicioAuth.usuario[] @return;
        
        public getAllUsersResponse()
        {
        }
        
        public getAllUsersResponse(servicioAuth.usuario[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createUser", WrapperNamespace="http://soap.auth.pe.dentalflow.com/", IsWrapped=true)]
    public partial class createUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.auth.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.auth.pe.dentalflow.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.auth.pe.dentalflow.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rolId;
        
        public createUserRequest()
        {
        }
        
        public createUserRequest(string username, string password, int rolId)
        {
            this.username = username;
            this.password = password;
            this.rolId = rolId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createUserResponse", WrapperNamespace="http://soap.auth.pe.dentalflow.com/", IsWrapped=true)]
    public partial class createUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.auth.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public servicioAuth.usuario @return;
        
        public createUserResponse()
        {
        }
        
        public createUserResponse(servicioAuth.usuario @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateUser", WrapperNamespace="http://soap.auth.pe.dentalflow.com/", IsWrapped=true)]
    public partial class updateUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.auth.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.auth.pe.dentalflow.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.auth.pe.dentalflow.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rolId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.auth.pe.dentalflow.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activo;
        
        public updateUserRequest()
        {
        }
        
        public updateUserRequest(int userId, string username, int rolId, bool activo)
        {
            this.userId = userId;
            this.username = username;
            this.rolId = rolId;
            this.activo = activo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateUserResponse", WrapperNamespace="http://soap.auth.pe.dentalflow.com/", IsWrapped=true)]
    public partial class updateUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.auth.pe.dentalflow.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public servicioAuth.usuario @return;
        
        public updateUserResponse()
        {
        }
        
        public updateUserResponse(servicioAuth.usuario @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface AuthEndpointChannel : servicioAuth.AuthEndpoint, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class AuthEndpointClient : System.ServiceModel.ClientBase<servicioAuth.AuthEndpoint>, servicioAuth.AuthEndpoint
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AuthEndpointClient() : 
                base(AuthEndpointClient.GetDefaultBinding(), AuthEndpointClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AuthEndpointPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthEndpointClient(EndpointConfiguration endpointConfiguration) : 
                base(AuthEndpointClient.GetBindingForEndpoint(endpointConfiguration), AuthEndpointClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthEndpointClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AuthEndpointClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthEndpointClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AuthEndpointClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<servicioAuth.loginResponse> servicioAuth.AuthEndpoint.loginAsync(servicioAuth.loginRequest request)
        {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<servicioAuth.loginResponse> loginAsync(string username, string password)
        {
            servicioAuth.loginRequest inValue = new servicioAuth.loginRequest();
            inValue.username = username;
            inValue.password = password;
            return ((servicioAuth.AuthEndpoint)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<servicioAuth.disableUserResponse> servicioAuth.AuthEndpoint.disableUserAsync(servicioAuth.disableUserRequest request)
        {
            return base.Channel.disableUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<servicioAuth.disableUserResponse> disableUserAsync(int userId)
        {
            servicioAuth.disableUserRequest inValue = new servicioAuth.disableUserRequest();
            inValue.userId = userId;
            return ((servicioAuth.AuthEndpoint)(this)).disableUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<servicioAuth.getAllUsersResponse> servicioAuth.AuthEndpoint.getAllUsersAsync(servicioAuth.getAllUsersRequest request)
        {
            return base.Channel.getAllUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<servicioAuth.getAllUsersResponse> getAllUsersAsync()
        {
            servicioAuth.getAllUsersRequest inValue = new servicioAuth.getAllUsersRequest();
            return ((servicioAuth.AuthEndpoint)(this)).getAllUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<servicioAuth.createUserResponse> servicioAuth.AuthEndpoint.createUserAsync(servicioAuth.createUserRequest request)
        {
            return base.Channel.createUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<servicioAuth.createUserResponse> createUserAsync(string username, string password, int rolId)
        {
            servicioAuth.createUserRequest inValue = new servicioAuth.createUserRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.rolId = rolId;
            return ((servicioAuth.AuthEndpoint)(this)).createUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<servicioAuth.updateUserResponse> servicioAuth.AuthEndpoint.updateUserAsync(servicioAuth.updateUserRequest request)
        {
            return base.Channel.updateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<servicioAuth.updateUserResponse> updateUserAsync(int userId, string username, int rolId, bool activo)
        {
            servicioAuth.updateUserRequest inValue = new servicioAuth.updateUserRequest();
            inValue.userId = userId;
            inValue.username = username;
            inValue.rolId = rolId;
            inValue.activo = activo;
            return ((servicioAuth.AuthEndpoint)(this)).updateUserAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AuthEndpointPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AuthEndpointPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:1520/ws/Auth");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AuthEndpointClient.GetBindingForEndpoint(EndpointConfiguration.AuthEndpointPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AuthEndpointClient.GetEndpointAddress(EndpointConfiguration.AuthEndpointPort);
        }
        
        public enum EndpointConfiguration
        {
            
            AuthEndpointPort,
        }
    }
}
